### ISSUE TITLE
Footer Shop-Mailadresse

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#101]
im Footer der automatisch generierten Bestellbestätigungen aus dem Shop steht noch die Brunnenstr. drin. Ich habe nach der entsprechenden Einstellung im Shop gesucht, aber nichts gefunden. Kannst du das ändern bzw. mir sagen, wo ich das finden kann?

**Comment by divanke** [comment]
Oh ja, da ist Presta-Shop nicht besonders intuitiv ... Du findest die Mail-Vorlagen unter:
Lokalisierung -> Übersetzungen -> Übersetzungen ändern -> Programmteil: E-Mail-Vorlagen, Template: classic-sub, Sprache: Deutsch (bearbeiten) -> Vordefinierte emails -> order_conf 
Ich hab es dort schon in Stefanstr. geändert. Aber ich hab nicht überprüft, ob andere Vorlagen auch noch die falsche Adresse beinhalten ...
