### ISSUE TITLE
popups

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#104]
Kann es sein, dass die Popups schon vor ner Weile verschwunden sind? Auf denen für Artikelspenden geworben wird? Ich hab mich ausggeloggt und ein bisschen rumgeklickt, es kommt keins. Liegt an meinen Browser-Einstellungen oder ist da was schief gelaufen? Meine Kolleg*innen berichten ähnliches.

**Comment by divanke** [comment]
Oh, ja könnte sein ... ich erinnere mich, dass das Modul mal ein update hatte. Tut mir leid, dass es mir nicht aufgefallen ist! Jetzt läuft es wieder (zumindest bei mir), obwohl mir nicht ganz klar ist warum: ich habe nirgendwo fehlerhafte Einstellungen gefunden, nur bei dem Intervall, wie häufig es wieder angezeigt wurde, war sowohl 0 (für jedes mal) als auch alle 10 Besuche angegeben - das hat sich eventuell mit der neuen Version widersprochen, so dass es gar nicht mehr angezeigt wurde?! Jetzt hab ich die 0 rausgenommen und stattdessen 1 eingetragen und jetzt wird es wieder angezeigt. Gib mir gern feedback, ob es so funktionert, wie gedacht. (Das war unter Konfiguration -> Media -> Simple Popups -> manage -> edit : visit counts )

**Comment by ibartram** [comment]
Wenn man auf "nein, diesmal nicht" klickt passiert leider nichts :)
