### ISSUE TITLE
Adminrechte

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#106]
Könntest du bitte Janina die gleichen Adminrechte wie mir geben? Ich bin mir nicht mehr ganz sicher worum es ihr ging, vielleicht neue User erstellen, auf jedenfall gab es den Fall dass ich im Urlaub war und sie etwas mache musste was nur ich kann. Danke!

**Comment by divanke** [comment]
Ihr habt beide die Rolle Redaktionsadmin und damit die gleichen Rechte. Janina kann sich gern bei mir melden, wenn sie feststellt, dass ihr Berechtigungen für bestimmte Sachen fehlen.
