### ISSUE TITLE
Alte durch neue Adresse ersetzen im Shop

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#111]
Ich hab unsere neue Adresse im Shop eingetragen, aber trotzdem wird die alte sowohl im Footer bei "Kontakt" als auch in den automatisch generierten Rechnungen angezeigt? Was mache ich falsch?
Die neue ist
Gen-ethisches Netzwerk e.V.
Lausitzer Straße 10, Aufgang B, 10999 Berlin

**Comment by divanke** [comment]
Ohje. Ja, mal wieder mühsam: im Prestashop verstecken sich viele Details in den einzelnen Modulen. Die Adresse bei "Kontakt" konnte ich in Voreinstellungen -> CMS-Seiten -> Kontakt verändern. Die Adresse im Footer ließ sich verändern bei Module -> Block Kontaktinformationen. Hast du eine Idee, wie die PDFs erstellt werden? Wenn ich unter Bestellungen -> Rechnungen schaue und mir die letzte anzeigen lasse, hat die von gestern (30.7.) die aktuelle Adresse drin. Oder meinst du etwas anderes?

**Comment by ibartram** [comment]
Super Danke! Cool dass es mit der neuen Adresse im rechnungspdf plötzlich auch geklappt hat ohne dass ich weiß warum...
