### ISSUE TITLE
Seite mit Passwort

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#114]
Könntest du bitte wieder ein passwort einrichten für die Webseite www.gen-ethisches-netzwerk.de/mv ? Und zwar xxx - Danke!

**Comment by divanke** [comment]
Hallo Isabelle, hab es eingerichtet. Dieses Ticketsystem ist öffentlich - nächstes Mal lieber direkt an mich per Mail. Und hier oben nachträglich pw entfernen... ;)

**Comment by divanke** [comment]
Du müsstest auch die Berechtigung haben, das selbst einzurichten: Configuration -> System -> Protected Pages: Seite eintragen, Passwort eintragen.

**Comment by ibartram** [comment]
danke!
