### ISSUE TITLE
Mail weiterleitung shop adresse?

### ISSUE THREAD

**Issue by divanke** [gengid/ticket#117]
Heute sind zwei Nachrichten angekommen, die darauf hinweisen, dass Cornelia Gutekunst keinen Account mehr bei euch hat, aber noch Weiterleitungen vom Shop auf diese Mailadresse gehen ... könntest du das mal überprüfen? Oder delegieren? Danke!

**Comment by ibartram** [comment]
ich schau es mir an, danke für den hinweis!

**Comment by ibartram** [comment]
hab ich gelöscht endlich
