### ISSUE TITLE
Komma bei mehreren Autor*innen

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#118]
Hey, an vielen stellen (z.B. Startseite), aber seltsamerweise nicht allen, wird bei Artikeln mit mehreren Autor*innen kein Komma dazwischen angezeigt. das sieht unschön/verwirrend aus, könntest du das bitte ändern? danke!

**Comment by divanke** [comment]
Ach, es gibt einfach zu viele verschieden Listentypen ... hatte einen der Typen vergessen anzupassen. Jetzt sollte es durchgehend richtig sein. Sorry!

**Comment by ibartram** [comment]
hier fehlt wieder das komma https://www.gen-ethisches-netzwerk.de/publikationen/gid/266
zb bei  Kritische Reflexionen statt einfache Positionen

**Comment by divanke** [comment]
Danke! Jetzt ist es da. Ich hoffe, es passt jetzt bei allen Listen ...
