### ISSUE TITLE
alte Infos im Shop

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#119]
Hab im Shop noch die alte Adresse entdeckt
https://shop.gen-ethisches-netzwerk.de/content/3-allgemeine-geschaeftsbedingungen

Hier stehen  auch noch alte Vorstände drin 
https://shop.gen-ethisches-netzwerk.de/content/6-datenschutzerklaerung
das sind die neuen: https://www.gen-ethisches-netzwerk.de/vorstand-und-beirat-0

Ich sehe elider nicht wo ich das ändern kann im Backend

**Comment by divanke** [comment]
Das geht über Voreinstellungen -> CMS-Seiten. Nicht besonders intuitiv. Hab ich gemacht.
