### ISSUE TITLE
Rechnungen Shop

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#120]
Lissy wünscht sich, dass in den Rechnungen die automatisch im Shop erstellt werden bei "Zahlungsinfo" unter "Reference:" (gern auch auf deutsch, also "Verwendungszweck:") die Rechnungsnummer erscheint und nicht diese komische willkürliche Buchstabenreihenfolge. Geht das? Danke!

**Comment by divanke** [comment]
Hm, ich kann nur die Zeile ganz raus nehmen, oder "Verwendungszweck: s.o." hinschreiben. Ich hab leider nicht herausgefunden, wie ich in dem Template des Moduls, was diesen einen Kasten im PDF erscheinen lässt, auf die Rechnungsnummer zugreifen kann. 
Und es kann sein, dass das bei der nächsten Aktualisierung des Moduls wieder auftaucht ... Aber besser als nix, oder?

**Comment by ibartram** [comment]
Vielelicht kannst du "Verwendungszweck: Rechnungsnummer, siehe oben" hinschreiben
