### ISSUE TITLE
AutorInnen-Beschreibung: Abstände

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#20]
Bei Auflistung mehrerer AutorInnen-Beschreibungen neben dem Artikel gibt es keinen Abstand zwischen ihnen. Dadurch dass es einen Abstand zwischen der Beschreibung und "zur Artikelübersicht" gibt sieht es komisch aus. Ich glaube besser wäre die leere Zeile zwischen "zur Artikelübersicht" und Beschreibung wegzumachen und dafür eine zwischen den AutorInnen einzufügen.
Beispiel: http://www.gen-ethisches-netzwerk.de/reprotechnologien/selbstbestimmungskritik/das-kind-als-projekt

**Comment by divanke** [comment]
Ich habe einen Abstand unter "zur Artikelübersicht" eingefügt. Der Abstand oberhalb lässt sich nicht so einfach entfernen. Ist es so okay? Der Abstand unter "zur Artikelübersicht" könnte noch vergrößert werden, um die Gruppierung deutlicher zu machen.

**Comment by ibartram** [comment]
ja, das ist gut so!
