### ISSUE TITLE
von / Interview mit ...

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#32]
jetzt steht da bei Interviews "von Interview mit xy"

Wir fänden es ja eh gut diese ganzen "interview mit" Namen aufzulösen und die als normale AutorInnen aufzuführen. Ein Lösungsvorschlag: Beim editor vor dem AutorIn-Feld ein Drop-down-Menü bei dem man auswähen kann zwischen "Interview mit" "von" und "mit"

Wär das möglich? Wenn das so eingerichtet wäre, würd ich mich drum kümmern, die ganzen bestehenden "interview mit" sachen umzuwandeln. "mit" braucht zb. bei dem Gespräch zwischen Paule und mir im aktuellen GID, da passt weder "von" noch "Interview mit"

**Comment by divanke** [comment]
Ich habe ein Dropdown-Menu mit "Von", "Interview mit" und "Mit" bei Online-Artikel und GiD-Artikel eingefügt. Jetzt kann dort das Präfix ausgewählt werden. Das "Von", das bislang an der Stelle eingefügt wird, habe ich erstmal noch nicht entfernt, weil das zur Folge hat, dass dann bei allen Artikeln dieses Präfix nachträglich eingestellt werden muss. Das per Hand zu machen ist für alle Artikel ja sehr mühsam. Vielleicht ist es aber auch nicht schlimm, wenn das Präfix erstmal fehlt und nur in neuen Artikeln hinzugefügt wird. Was meinst du, wie weiter?

**Comment by ibartram** [comment]
Danke! 
Ich würde erstmal mit den anderen reden ob sie das Ok finden wenn das "von" bei alten Artikeln fehlt, oder ob jemand Zeit und Kapazitäten hätte die Einstellung rückwirkend für alle Artikel zu machen weil mir dazu die Zeit fehlt.

Kann leider etwas dauern bis ich eine Antwort habe..

**Comment by divanke** [comment]
Ist gemacht. Falls dir noch Unregelmäßigkeiten auffallen, sag gern Bescheid!

**Comment by ibartram** [comment]
in der artikel-liste des neuen gid ist seltsamerweise ein absatz zwischen "von" bzw. "interview mit" und dem autor_innen-namen - lässt sich der entfernen?
https://gen-ethisches-netzwerk.de/publikationen/gid/247

**Comment by divanke** [comment]
Hab ich entfernt. Sorry, dass ich das übersehen habe.
