### ISSUE TITLE
Menüs auswahl Themen, Stichwörter, AutorInnen

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#35]
Ich glaube seit dem Update? sind die Menüs zur Auswahl der der Wörter wieder so ungünstig beim Artikel erstellen.

**Comment by divanke** [comment]
Was meinst du mit ungünstig? Wie war es denn vorher bzw wie soll es sein? Ich nehme an, es geht um GID-Artikel und Online-Artikel erstellen.
