### ISSUE TITLE
Anzeige Themen-Begriffe bei GID-Artikeln

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#36]
Bei Online-Artikel werden die Themen unter den Stichwörtern angezeigt, bei den GID-Artikeln aber nicht. Es wäre schön, wenn auch bei den GID-Artikeln die Themen-Begriffe angeziegt würden.

Beispiele:
GID-Artikel https://gen-ethisches-netzwerk.de/wissenschaftskritik/fehlende-gewissheiten
Online-Artikel: https://gen-ethisches-netzwerk.de/august-2018/brasilien-verbietet-glyphosat

**Comment by divanke** [comment]
Ist geschehen.
