### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#37]
Der Slider auf der Startseite ändert leider von angezeigten Artikel zu Artikel die Bildgröße und damit sein Format. Wahrscheinlich weil verschiedene Bildmaße für die jeweiligen Artikel hochgeladen wurden? Oder liegt es an der unterschiedlichen Länge der Titel/Untertitel? Ist es möglich, es so zu ändern, dass im Slider angezeigte Bidler automatisch auf eine bestimmte Größe/Dimension zugeschnitten werden?

**Comment by divanke** [comment]
Ich schau mir das Ende der Woche an.

**Comment by divanke** [comment]
Ich hab es mir doch jetzt schon angesehen. Jetzt werden die Bilder im Slider auf die gleiche Größe Skaliert und zugeschnitten.

**Comment by ibartram** [comment]
toll :D
