### ISSUE TITLE
Shop Titelbild "Medien"

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#38]
Beim Shop ist das Titelbild von "Medien" irengdwie seit einer Weile größer als das der anderen Kategorien. Lässt sich das ändern? Ich habe gestern versucht zu gucken wo ich das ändern kann, habs aber nicht gefunden, vl weil ich die Rechte nicht hab oder vl hab ichs eincah übersehen? Köntest du dir das mal angucken? Nicht super dringend. danke!

**Comment by ibartram** [comment]
Hast du dir das mal angeguckt? Ich habe neulich gefunden wo man die Bilder ändert, aber die einstellung der richtigen Pixelzahl hat irgendwie nix gebracht. Jetzt finde ich nicht mal mehr wo ist das eingestellt hatte... alles sehr verwirrend ;) ich nehm jetzt erstmal die kategorie raus weil die beiden filme eh kaum gekauft werden.

**Comment by ibartram** [comment]
also irgendwie kann man die kategorie nicht rausnhemen... nur die artikel werden unsichtbar. irgendwo muss es doch einstellstellbar sein wie die startseite des shops aussieht... ich markier das mal als "dringend", ist wirklich optisch nicht so schön. (oder sieht da sbei dir anders aus?)

**Comment by divanke** [comment]
Ich habe die Stelle im css code gefunden, an der dem  fünften Element die doppelte Breite zugewiesen wurde und hab das auskommentiert ... das war mühsam zu finden, aber jetzt siehts gut aus :)

**Comment by ibartram** [comment]
ganz toll!! :) danke!
