### ISSUE TITLE
GID-Titelbild auf Startseite verlinken

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#39]
Gerade ist das Bild in dem Block "Die aktuelle Ausgabe des GID" nicht verlinkt. Man kommt nur zu dem GID wenn man auf den Titel klickt, das ist eher unintuitiv. Könntest dus so einstellen, das das Titelbild mit der jeweiligen GID-Inhaltsseite verlinkt ist?

**Comment by divanke** [comment]
Ist gelöst. 
Vielleicht ist da beim Erstellen Konfusion entstanden, weil es auch einen Artikel mit dem Titel gibt? Der Block war zumindest anders aufgebaut als bei vorherigen Ausgaben (konnte es mit meiner lokalen Version vergleichen ...)
