### ISSUE TITLE
Kästen bei Online-Artikel

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#40]
Ich habe gerad einen Online-Artikel eingestellt, der noch nicht veröffentlicht sein sein soll. Mit dem Admin-Account kannst du ihn wahrscheinlich trptzdem sehen oder? https://gen-ethisches-netzwerk.de/oktober-2018/die-personalisierung-der-depression

Auf jeden Fall ist da ein Kasten in den ich die Literaturangaben gesetzt hab. Dabei ist mir aufgefallen, dass die Kästen noch nicht so sind wie wir das gedacht hatten.

Könntest du 
- die Überschrift "Kasten_1", "Kasten_2" etc. für alle 3 Kästen entfernen? 
- den 3. Kasten so anlegen, dass er unter statt neben dem Artikel erscheint?

Danke! Der Artikel soll erst Mitte Oktober veröffentlicht werden, hat also Zeit.

**Comment by divanke** [comment]
Schau mal rein, ob es jetzt so ist, wie gewünscht. Ich hab die drei Überschriften entfernt und den dritten Kasten unter den Artikel sortiert. Der ist allerdings noch leer, daher nicht zu sehen.

**Comment by divanke** [comment]
Ja, ich habe die Begrenzung enfernt, jetzt werden alle Literaturangaben im Kasten 3 angezeigt.
