### ISSUE TITLE
Auswahl Drop-Down-Menü

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#41]
Auf dieser Seite lässt sich in dem Dop-Down-Menü nur 2016 oder 2017 auswählen, es sind aber auch Beiträge von 2018 dabei
https://gen-ethisches-netzwerk.de/ueber-uns/pressespiegel

Bei Pressemitteilungen ist das selbe Problem, außerdem sieht das "Themen"-Dropdown-Menü irgendwie hässlich aus, so leicht nach unten verschoben, lässt sich das reparieren?
https://gen-ethisches-netzwerk.de/pressemitteilungen

Danke!

**Comment by ibartram** [comment]
Oh und bei der Liste von Artikeln bei Pressemitteilungen steht immer "Bild" und dnan der Titel vom Bild - kann das weg?

**Comment by divanke** [comment]
Ich habe das Dropdownmenü erweitert, bei Pressemitteilungen, Pressespiegel und auch bei den Themen. Die Bild-Texte bei Pressemitteilungen sind auch entfernt. 

Dass das Themen-Dropdown-Menü verschoben ist, kann ich nicht so leicht ändern. Würde ich erstmal hinten an stellen.

**Comment by ibartram** [comment]
Toll, Danke!
