### ISSUE TITLE
embed identity

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#42]
https://gen-ethisches-netzwerk.de/taxonomy/term/2659

Im Sidebar hier zum Beispiel kann man den GID-Ausgabe einbetten, für die gewählte Darstellung ist der Typ "GID Inhalt Embed entity" ausgewählt. Könnte man es so einstellen, dass bei diesem Einbettungstyp  das GID-Cover mit der GID-Inhaltsseite verlinkt ist und nicht nur die Überschrift? jetzt ist es nur mit dem GID-Cover-Bild verlinkt. Also ähnlicher Issue wie das schon gelöste mit dem GID-Cover auf der Startseite.

**Comment by divanke** [comment]
Jetzt ist das Bild mit der GID-Ausgabe verlinkt.
