### ISSUE TITLE
Datum bei Online-Artikeln

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#43]
Bei den GID-Artikeln stehen ja die GID-Nummern da, bei den Online-Artikel ist das Datum leider nicht zu sehen. Es wr aber gut wenn Leser_innen gelich sehen können wie aktuell ein Artikel ist.

Bsp. https://gen-ethisches-netzwerk.de/mai-2018/golden-state-killer

Könntest du das Einstellungsdatum einfügen, und zwar als Block unter der Autor_innenbeschreibung? Also zwischen Autor_in und Stochwörtern? Format wie in Listenasicht, also  "2. Oktober 2018" 
Danke!

**Comment by divanke** [comment]
Bei den Online-Artikeln gibt es jetzt rechts unter der Autor*innenbeschreibung einen grauen Kasten mit Datum
