### ISSUE TITLE
Überschrift "Unterstützer*innen"-Seite 

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#44]
Wir haben jetzt endlich auf * -Genderung umgestellt :) Ich weiß nicht wo ich den Inhalt der  "Unterstützer * innen"-Seite ändern kann. Könntest du die Überschrift "Unsere UnterstützerInnen" bitte in "Unsere Unterstützer * innen" ändern (ohne die Leerzeichen, die habe ich eingefügt weil Github Text mit Sternchen kursiv macht und die Sternchen nicht anzeigt)? Danke! 

https://gen-ethisches-netzwerk.de/unterstuetzerinnen

**Comment by divanke** [comment]
Habe ich geändert, auch auf der Startseite im Block unten rechts.
