### ISSUE TITLE
Twitter: Artikelbild importieren

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#45]
Gerade zeigt Twitter wieder nicht das Artikelbild neben dem Titel & teaser an, wenn man einen Artikel der Webseite verlinkt. Das Problem hatten wir schon 2x mal, einmal wurde es gelöst durch andere einstellungen auf der GeN-Seite. Einmal hat es sich von alleine gelöst, da war es vl n Fehler bei Twitter.

zb. https://twitter.com/GeNetzwerk/status/1052489347562463232

**Comment by divanke** [comment]
Ich habe keine Idee, woran das liegt. Weißt du, seit wann das so ist? Werden auch bei alten Artikeln, die früher mit Bild angezeigt wurden, die Bilder nicht angezeigt? 
Auch von anderen tweets werden die Artikelbilder nicht angezeigt: 
[https://twitter.com/GeNetzwerk/status/1052209846144167942]
Insofern würde ich hoffen, dass es sich "von allein" löst ... oder mich ggf in zwei Wochen nochmal ransetzen.

**Comment by ibartram** [comment]
na hier zb. klappt es https://twitter.com/GeNetzwerk/status/1049580948566757376
aber so in klein

normalerweise sind die ja so groß, zb. so
https://twitter.com/GeNetzwerk/status/1045666317817335810

**Comment by divanke** [comment]
Ich kenne mich mit twitter nicht aus, weiß nicht, wie die die Bilder einbinden und wie es beeinflusst werden kann, welches Bild wie angezeigt wird.

**Comment by divanke** [comment]
Ich kenne mich mit twitter nicht aus, weiß nicht, wie die die Bilder einbinden und wie es beeinflusst werden kann, welches Bild wie angezeigt wird.

**Comment by ibartram** [comment]
vl kann man das in irgendnem drupal-nerd-forum fragen?

ich hab sonst mal ein paar sachen ergoogelt, ich weiß nicht ob das dir weiterhilft. ich kenne die dupal-"fachsprache" nicht richtig, daher weiß ich nicht genau wonach man suchen muss

Add Twitter Cards metadata
https://www.drupal.org/project/dvg/issues/2798667

man kann bei twitter durch den "twitter card valdidator" checken ob ein fehler bei der jemweiligen seite ist 
https://cards-dev.twitter.com/validator

Bei der Seite sagt es mir

"INFO:  Page fetched successfully
INFO:  27 metatags were found
INFO:  twitter:card = summary_large_image tag found
INFO:  Card loaded successfully"

aber trotzdem wird das bild nicht angezeigt? komisch

**Comment by divanke** [comment]
Das Modul Twitter Cards metadata ist installiert und aktiv. Ich habe kleine Modifikationen daran vorgenommen, vielleicht hilft das für neue tweets. 
Die Ausgabe des validators sieht doch gut aus. Ich finds auch komisch.

**Comment by divanke** [comment]
Nochmal gesucht und eine troubleshooting seite von twitter gefunden. Da steht folgendes:
"Card Display Issues - My Tweet is missing the image/video/summary text.
There are a number of possible reasons for this. Here are some suggestions and ways to troubleshoot:
    Your Player Card has yet to be whitelisted. Please run your example URL through the Card Validator, and click the Request Approval button to begin the whitelist process."
Offenbar hattest du den validator schon benutzt - was ist mit dem whitelist process? Könntest du den nochmal anstoßen? https://cards-dev.twitter.com/validator 
Vermutlich auch gleich für http://gen-ethisches-netzwerk.de und nicht nur für die einzelnen Artikel. 
Danke!

**Comment by ibartram** [comment]
also wenn ich gen-ethisches-netzwerk.de eingebe kommt das:

INFO:  Page fetched successfully
INFO:  8 metatags were found
INFO:  twitter:card = summary tag found
ERROR: Possibly invalid value (if specified) (og:title)
ERROR: Possibly invalid value (if specified) (twitter:text:title)
ERROR: Possibly invalid value (if specified) (twitter:title)

Wenn ich https://gen-ethisches-netzwerk.de/oktober-2018/die-personalisierung-der-depression eingebe kommt das:

The card for your website will look a little something like this!
Unable to render Card preview

INFO:  Page fetched successfully
INFO:  2 metatags were found
ERROR: No card found (Card error)

**Comment by ibartram** [comment]
Er sagt 

INFO:  Page fetched successfully
INFO:  27 metatags were found
INFO:  twitter:card = summary_large_image tag found
INFO:  Card loaded successfully

Offensichtlich aber nicht "Card loaded successfully" weil kein Bild :( Kirsten berichtet dass es bei Facebook auch nicht klappt.. Vl müssen wir irgendeinen Zugriff zu lassen?

**Comment by divanke** [comment]
Danke für deine weitere Recherche. Ich habe jetzt auch meine Fährte weiterverfolgt und habe etwas an den Einstellungen der Metatags geändert. Nun werden die adressen der Bilder korrekt in den metatags ausgegeben und sollten bei twitter  und fb geladen werdn können. Wenn ich jetzt den twitter stream neu lade, gibt es allerdings noch keine Veränderung. Vielleicht bei neuen Beiträgen oder wenn twitter die Artikel neu indiziert ? Ich würde nochmal eine Woche warten. 
Sorry, dass das so langwierig ist.

**Comment by divanke** [comment]
Bei diesem tweet wird das Bild angezeigt: 
https://twitter.com/GeNetzwerk/status/1067819512509140992
Ich habe nach Unterschieden gesucht und diesen gefunden:
Im Unterschied zu den anderen beginnt dieser link mit http://www. 
http://www.gen-ethisches-netzwerk.de/risikodebatte-und-risikomanagement/kein-wissenschaftlicher-konsens
statt z.B.
https://gen-ethisches-netzwerk.de/wissenschaftskritik/streit-um-evidenz

Könnte es also daran liegen, welcher Link beim twitter post angegeben wurde? Ich wäre dankbar, wenn du das bei Gelegenheit testen könntest und beim nächsten Post den link mit http://www angeben würdest... Danke!
