### ISSUE TITLE
Matomo/Piwik braucht Update?

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#46]
Das Statistik-tool sagt wenn ich mich einlogge "Piwik 3.6.1 ist verfügbar. Bitte benachrichtigen Sie den Matomo Administrator. Sie nutzen derzeit Matomo 3.6.0."

Ich hoffe du hast den Administrator-Login dafür bekommen?

**Comment by ibartram** [comment]
Also wenn es nötig ist upzudaten, ich kann es nicht einschätzen, was meinst du?

**Comment by divanke** [comment]
Danke für den Hinweis, ich habe es aktualisiert.
