### ISSUE TITLE
artikel ausschließen von startseite

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#47]
Beim Erstellen von GID-Artikeln gibt es die Möglichkeit den Artikel von der Startseite auszuschließen durch ein Häkchen unten bei " Filter: Ausschluss"

Könntest du sowas bitte auch bei Online-Artikeln einführen?

Danke!

**Comment by divanke** [comment]
Ich habe den Filter nun auch bei Online-Artikeln eingefügt.
