### ISSUE TITLE
probleme im c-panel

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#48]
das c-panel sagt: Alarm weil
physischer Speicherverbrauch
864,7 MB / 1 GB (84,44%)

Also einige e-mail-accounts haben schon mehr als 1.GB größe - was soll also diese zahl heißen? muss ich was machen? 

und was ist 

I/O Nutzung
3,85 MB/s / 4 MB/s (96,34%)

?? da ist auch Alarm

**Comment by divanke** [comment]
Hallo Isabelle, 
diese Warnungen im cpanel treten auf, wenn ich an der Seite updates mache - das ist normal bzw okay so. Das was als physikalischer Speicherverbrauch benannt ist, ist der Arbeitsspeicherverbrauch, in der englischen Anzeige mit physical memory usage benannt - das hat nichts mit den e-mail-accounts zu tun, die füllen das, was in der englischen Anzeige mit disk usage benannt ist, in der  deutschen Anzeige heißt das Speicherplatznutzung. Die deutsche Übersetzung ist nicht so eindeutig an der Stelle. 
Liebe Grüße, 
Anke
