### ISSUE TITLE
Bezahlung für Online-Artikel

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#49]
Das ist jetzt eher was langfristiges zum überlegen... Im angesicht sinkender Printzahlen und immer weiter steigenden Online-Zahlen wollen wir, dass Leute für Online-Artikel freiwillig zahlen sollen/können... Vl mit sonem Pop-up wenn man die Seite besucht. Gleichzeitig wollen wir, dass Pressemitteilungen natürlich möglichst ohne nervige Störung lesbar sind.

Wir haben auch so ein Online-Spendentool was kaum jemand benutzt, Twingel, da könnte man sicher ein Projekt anlegen und in so einen Popup einbauen mit 2 Euro oder so voreingestellt. Da müsste man dann aber wohl sofortüberweisung oder sowas dazu kaufen damit das attraktiver zu benutzten ist. 

Ein Login der ansonsten nicht freigeschaltete Artikel lesbar macht wäre natürlich auch eine Lösung. Aber wir wollen ja eigentlich dass möglichst viele Leute unsere Infos lesen, notfalls umsonst, und überlegen eher grundsätzlich alle Artikel sofort freizuschalten.

Wir werden nochmal in der Redaktion in Ruhe drüber reden wie wir das genau wollen. Aber wenn du sowas schonmal irgendwo angelegt hast oder dir was über den Weg läuft wie man es machen könnte oder wie es bei anderen Publikationsprojekten klappt, würden wir uns über Expertise freuen.

**Comment by divanke** [comment]
Danke für die langfristige Ankündigung - ich kann im Januar mal schauen, was da möglich wäre.

**Comment by ibartram** [comment]
So wir haben das Them nun mal vorsichtig andiskutiert, mehr wird folgen, aber dafür brauchen wir Infos über technische Machbarkeit.

Idee 1:
- alle Artikel göeich freischalten, wegklickbares Popup bei Artikeln auf dem das Spendentool der GLS-Bank (siehe /spenden) einbaut ist, zähler steht auf 5 euro oder. Technisch wahrscheinlich easy, aber ginge es hier Pressemitteilungen davon auszuschließen? Weil wir wollen ja, dass die möglichst viel gelesen werden.

Idee 2: einige Texte hinter einer Bezahlschranke - also gegen sofortiger Zahlung von 2-5 Euro oder so doch lesbar. Geht sowas?

Idee 3: ?? hats du noch ne Idee?

**Comment by ibartram** [comment]
Siehe anderes Ticket: Wir haben am 27. ein Treffen wo wir weiter beraten wollen, dafür bräuchten wir Infos über die technische Machbarkeit unserer Ideen. Hättest du Zeit bis dahin dazu was zu sagen?

**Comment by divanke** [comment]
Die Idee 1 ist relativ einfach machbar. Das ließe sich auf unterschiedliche Kategorien Beschränken: GiD-Artikel, Online-Artikel, etc, dabei können Pressemitteilungen ausgeschlossen werden. Bei der Taz finde ich es z.B. ganz okay gelöst. Könntest du mir den Twingle-Zugang geben, damit ich dort schauen kann, welche Optionen es dort noch gibt? Momentan ist die untere Grenze bei 5 Euro - wenn das Tool keine kleineren Beträge erlaubt, wäre es gut, noch nach einer Alternative zu suchen ... PayPal hat relativ hohe Gebühren, Sofortüberweisung noch höhere, wenn ich das hier richtig lese: https://documents.sofort.com/tarife/sofort/

Zu der Bezahlschranke: Ich habe kein aktuelles(!) Modul gefunden, dass diese Möglichkeit zur Verfügung stellt, mit etwas Aufwand sollte es trotzdem möglich sein. Ich frage mich nur, ob diese Bezahlschranke dann auch für Fördermitglieder gilt/gelten soll. Wenn nicht, müsste es so etwas wie ein Login für Fördermitglieder geben, was den Aufwand deutlich erhöht. Und es wird spannend, welche Lösung wir finden, dass sich Fördermiglieder aus der Zeit vor der Login-Einführung registrieren können ... also einige Hürden.

Weitere Ideen hab ich nicht. Das Modell der Taz ist mir sympathisch - wenn ihr möchtet, könnte ich versuchen nachzufragen, wie zufrieden sie dort mit der Lösung sind ...

**Comment by ibartram** [comment]
Also es sieht nach Variante 1 aus - ich geb dir gerne den Twingle Zugang. Ich schreib dir ne Mail.

**Comment by ibartram** [comment]
Silvia war ja schon deshalb mit dir in Kontakt. Wir haben folgendes beschlossen:

**Pop-up-Fenster** mit der Frage, ob mensch für den zu lesenden Artikel zahlen möchte (Ja – Verweis zu Spendentool, Nein – Fenster schließt sich) . 
- GID-Artikel: Gilt nur für die ab sofort freigeschalteten Artikel. Alle anderen bleiben weiterhin eine zeitlang gesperrt
- Online-Artikel: Nicht bei Pressemitteilungen, Stellungnahmen, "in anderen Medien" > falls es nicht möglich ist, dass so differenziert einzustellen, dann nur bei Inhaltstyp "GID-Artikel"

Text: - liefer ich noch nach, vl erstmal "Bitte tragen Sie dazu bei, dass wir unsere Inhalte kostenlos anbieten können."




**Fragen:** 

- Was ist beim Einstellen neuer Artikel zu beachten? 
- Taucht das Pop-up-Fenster auch auf, bei Artikeln die später freigeschaltet werden (also zum Zeitpunkt wo sie dann freigeschaltet sind)?

**Comment by divanke** [comment]
Ich habe jetzt ein popup erstellt, es erscheint bei GeN-Artikeln und Online-Artikeln, aber nicht bei Pressemitteilungen, Stellungnahmen und "in anderen Medien". Damit es nicht zu sehr nervt, ist es jetzt so eingestellt, dass es nicht bei jedem Artikelaufruf auftaucht, sondern nur beim 1., 3., 7., 10., 15., 20. und dann alle 10 Aufrufe. Ist das so okay, oder wird es so zu unklar, warum und wann dieses popup auftaucht?

Ist die Optik okay? braucht es noch eine Überschrift?

Ich habe erstmal nur auf die Spendenseite verwiesen, das mit dem zweiten twingle-projekt schau ich mir noch an.

**Comment by divanke** [comment]
Ich habe jetzt doch noch ein neues Twingle-Projekt erstellt, auf das jetzt verwiesen wird. Schaut euch bitte an, wie das funktioniert - da sind so viele Variablen drin ...
- Spendenrahmen 1-500, Voreinstellung 5
- Spendenseite von twingle öffnet in neuem Tab, auf dem alten Tab wird Spendenaufruf geschlossen und der Artikel ist lesbar

Ah, ich hatte vergessen zu erwähnen, dass das Popup erst nach 4 Sekunden erscheint - passt das, oder länger oder lieber direkt?

**Comment by ibartram** [comment]
Vielen Dank!
Wir haben kurz drüber geredet und werden uns noch mal länger damit beschäftigen, aber bis dahin haben wir folgende Antworten auf deine Fragen:

- nicht bei jedem Artikelaufruf: gut
- nach 4 sec: lieber sofort
- Twingle: gut
- Optik: wir hätten gern die Überschrift: "Nur durch Spenden ermöglicht!" erstmal, vl ändern wir die noch. Dann hätten wir gern noch ein Bild, darüber oder daneben. wenn es geht kannst du es so einstellen, dass das Bild in zufälliger Reihenfolge anders ist? Und zwar gerne die gleichen Bilder wie im Header: 

https://pixabay.com/photos/cow-farm-agriculture-animal-cattle-1562116/
https://pixabay.com/photos/medications-cure-tablets-pharmacy-257349/
https://pixabay.com/photos/corn-corn-on-the-cob-piston-young-1605664/
Das Bild mit der Demo finde ich nicht mehr, aber da können wir bestimmt noch eins nachreichen.

**Comment by ibartram** [comment]
Hey, wir haben nochmal besprochen: Wir würden gern neben den oben genannten Wünschen noch fragen, ob es möglich ist, das Popup bei jedem ersten Besuch eines Artikels auf der Webseite zu sehen? Bis wann könntest du die Wünsche umsetzen?

**Comment by divanke** [comment]
Hallo, 
einiges hatte ich schon eingebaut: das popup kommt jetzt sofort, die Überschrift ist verändert. Das mit dem wechselnden Bild hab ich mir noch nicht angeschaut, sollte aber machbar sein. Das schaffe ich hoffentlich noch diesen Monat... bin gerade mal wieder auf Tour.

Zu der Frequenz des Popups: so wie es gebaut ist, gilt der Zähler (erster, dritter, siebter etc Aufruf) für alle Artikel, nicht für die spezifischen. Um den Zähler für jeden Artikel einzeln zu starten, müsste ich tiefer in die Codestruktur des popup-plugins eintauchen - könnte ein paar Stunden Aufwand bedeuten. Einfacher ginge es, den Zähler nach einem Tag oder einer Woche verfallen zu lassen und beim nächsten Besuch von vorn zu starten - dann wäre es so was ähnliches wie bei jeden neuen Besuch bei gen-ethisches-netzwerk.de wird wieder nach einer Spende gefragt, aber während auf der Seite in verschiedenen Artikeln recherchiert wird, erscheint das popup nicht immer wieder. Wird deutlich, was ich meine?

**Comment by divanke** [comment]
Das Bild hab ich jetzt neben den Text eingefügt - hattet ihr das so gedacht? Ich habe den Header auseinandergeschnitten, so habe ich jetzt alle vier Bilder. 

Habt ihr schon über meine Einschätzung bezüglich der Frequenz der Popups und deren Implementierung gesprochen? Habt ihr dazu noch Fragen?

**Comment by ibartram** [comment]
Ich habe leider das Problem, dass bei mir das Popup gar nicht mehr angezeigt wird. Deshalb kann ich gerade auch gar nichts dazu sagen wie es mit dem Bild aussieht :)

Also aber bei der letzten Sitzung dazu haben wir besprochen, dass wir die Frequenz gerne so hätten wie du vorgeschlagen hast, also das sbei jedem Besuch neu gezälht wird. Gerade Leute die viel lesen bei uns können ruhig häufig dazu aufgefordert werden was zu zahlen.

**Comment by ibartram** [comment]
Also noch 2 Wünsche:
wir hätten gern die Bilder im Original, also nicht mit diesem Farbfilter über die Hälfte. Ich hatte sie dir ja mal verlinkt, siehe oben. 

und gerne als Knopf “Ja ich spende!” statt "ich will spenden", gerne auch größer als der Rest des textes und die "nein"-Option

Danke!

**Comment by divanke** [comment]
Die drei Bilder, die du mir verlinkt hattest, hab ich jetzt im Original eingefügt. Hast du das Demo-Bild noch gefunden? Da hab ich jetzt so gut es ging den Filter entfernt, geht vielleicht auch so. 
Der Text vom Ja-Button ist geändert und die Schrift in der Größe an die Überschrift angepasst. 
Wenn du den Browser schließt und wieder öffnest, sollte eine neue Session gestartet werden und damit das Spendenpopup wieder angezeigt werden. Es gibt Browser, die Session-Cookies als permanente Cookies behandeln - bei denen wird das Popup alle 10 Seitenaufrufe angezeigt.

**Comment by ibartram** [comment]
ich glaube wir sind erstmal so zufrieden, vielen Dank! :)
