### ISSUE TITLE
formatierung liste in kasten

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#50]
hier sind im kasten rechts die punkte von der liste so direkt am rand, kann man ein ganz kleines Stück anrücken? und vl kleiner abstand zwischen den absätzen?
https://gen-ethisches-netzwerk.de/politischer-einkaufskorb
danke!

**Comment by divanke** [comment]
Ich hab die Punkte jetzt auf eine Linie mit der sonstigen linken Textkante gebracht und einen kleinen Abstand zwischen die Unterpunkte. Passt das so?
