### ISSUE TITLE
Spendenaufforderung auf Startseite

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#52]
Könntest du nen Block einbauen auf der Startseite, in der Spalte rechts über dem Block "Die aktuelle Ausgabe des GID" wo das Spendentool der GLS-Bank drin ist? siehe /spenden - ich hoffe das tool sieht ok aus wenn es in sonem Block ist... 
Danke!!

**Comment by ibartram** [comment]
Wir haben nächste Woche ein Treffen wo's um die Webseite geht (27.), meinst du du hättest Zeit es bis dahin umzusetzen? Dann könnten wir da beraten ob wir es so gut finden.

**Comment by divanke** [comment]
Ich habe den Spendenblock eingefügt, er sieht okay aus finde ich. Aber entscheidet gern am 27. darüber!

**Comment by ibartram** [comment]
danke! ich sag dann bescheid!

**Comment by ibartram** [comment]
es würde der Wunsch geäußert den Spendenblock eins runter zu schieben , alos unter den aktuellen GID.

**Comment by divanke** [comment]
längst geschehen :)
