### ISSUE TITLE
URLS bei gleichem Artikel-Namen sind komisch

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#53]
Whaben festgestellt, dass viele alte GID-Artikel nicht zu den GID-Ausgaben zugeordnet sind. Das haben wir also aufgeteilt und versucht nachzuholen. Dabei tauchte folgendes seltsames Problem auf:

die GID-Artikel die in jeder Ausgabe immer gleich benannt sind "Materialen" "Termine" "Kurz notiert - Landwirtschaft und Lebensmittel" etc. haben immer die gleiche URL automatisch, bzw. eine Nummer dahinter, zB. "/materialien-42" Oft wiederholt sich die Numemr aber, so dass man zu "Materialien" einer anderen Ausgabe geleitet wird. Schwer zu erklären. Was hilft ist die betroffene Seite zu bearbeiten "Automatischen URL-Alias erzeugen" auszuschalten, so dass der Link /node/xxxx ist. 

Kann man da irgendwas machen? Rückwirkend geht das wohl nicht. Aber könnte man vl bei GID-Artikeln bewirken, dass in der automatischen URL die GID-Nummer einbeuat wird in Zukunft? Aber ohnen dass sich das für alle alten Artikel ändern, weil die werden ja auch auf anderen Seiten verlinkt.

Was denkst du?

**Comment by divanke** [comment]
Jetzt wird in die url der neuen GID-Artikel die GID-Nummer in folgendem Schema eingebaut: 
/thema1/thema2/gid-nr/artikel-titel
Ist die Reihenfolge so okay? Kann ich auch ändern. 
Falls ihr das bei anderen Artikeln angleichen wollt, könnt ihr unter "Content" die Artikel auswählen, dann "Veröffentlichung zurücknehmen", anwenden, "Veröffentlichen", anwenden. So werden die Artikel neu gespeichert und ihnen eine neue url zugewiesen. 
Ich habe außerdem ein neues Modul installiert, dass bei Veränderung der url automatisch einen redirect anlegt, so dass die Seiten auch noch unter der alten url gefunden werden können (z.B. wenn sie von einer anderen Seite aus verlinkt sind). 
Passt das so? Sind dann noch Wünsche offen? Sonst gern das ticket schließen.

**Comment by ibartram** [comment]
klappt, super, danke!
