### ISSUE TITLE
GeN-Seite/Server down?

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#55]
Irgendwie funktioniert gerade weder die Webseite noch die Mailadressen, weißt du woran es liegt / kannst Dennis fragen?

**Comment by divanke** [comment]
Bei mir läuft die Seite, ich prüfe mal, ob ich Fehler finde ...

**Comment by ibartram** [comment]
komisch, vl liegt es an unserem wlan? aber nur die gen-seite, der rest des internets funktioniert...

**Comment by ibartram** [comment]
auf allen computern laden weder die mails noch die seite, ich starte mal den rooter neu

**Comment by ibartram** [comment]
jetzt funktioniert es!! sorry für den fehlalarm!!!!
