### ISSUE TITLE
passwortgeschützten Ordner auf dem Server für Downloads

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#56]
Anfrage von Christof (ausführlich siehe Mail vom 18.03.2019)

"fuer den austausch v dateien nach dem treffen in naumburg benoetigen wir einen ordner, in dem wir dateien zum download anbieten koennen – aber nur nach eingabe v benutzer*innenname und passwort

es gibt eine funktion im cpanel – das ist unten in meiner mail beschrieben. ich hatte das nicht eingerichtet bekommen und deshalb dennis gefragt, da er ja das cpanel bereitstellt (as far as I know). er verweist in seiner antwort auf das cms"

**Comment by divanke** [comment]
Folgendes habe ich eben Christoph geschrieben:

Hallo Christof,

tut mir leid, dass deine Anfrage so lange bei mir liegenblieb. Leider war es nicht einfach, das einzurichten - bei mir auf der lokalen Installation lief es einwandfrei - so wie du es angelegt hattest, mit dem Filesharing-Ordner in files, der dann durch eine .htaccess-Datei passwortgeschützt ist - aber bei Dennis auf dem Server nicht. Warum das so ist haben wir beide nicht herausgefunden. Und statt jetzt noch länger nach einer Lösung dort zu suchen habe ich nun auf Dennis Vorschlag hin eine Subdomain eingerichtet, über die du Downloads bereitstellen kannst.

http://share.gen-ethisches-netzwerk.de

Dort habe ich gleich mal die Test-datei angelegt:

http://share.gen-ethisches-netzwerk.de/test.pdf

auf die du mit deinem damals angelegten Passwort zugreifen können müsstest. Du kannst dir aber auch beim c-panel ein neues anlegen. Dort kannst du auch den Anzeige-Namen des Verzeichnisses ändern - jetzt gerade lautet er Files.

Ist diese Lösung für dich okay? Falls du noch Fragen oder Wünsche hast, meld dich gern bei mir.

Liebe Grüße,

Anke
