### ISSUE TITLE
Dateien in Artikel einfügen

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#58]
Eigentlich sollte es möglich sein im Texteditor, wenn man einen Artikel erstellt, eine unter "Content>Medien hinzufügen>Datei" hochgeladenen Datei, z.B. ein PDF, auszuwählen und im Beitrag so als Button einzufügen. Dafür gibt's in der 2. Zeile im Texteditorauswahl den Button "Datei". Wenn ich das mache wird aber nur "select entities. Sie haben keine Zugriffsberechtigung für diese Seite." angezeigt. Ist das änderbar?

**Comment by divanke** [comment]
Da waren die Berechtigungen zu restriktiv. Jetzt geht es.
