### ISSUE TITLE
Disk usage mails

### ISSUE THREAD

**Issue by divanke** [gengid/ticket#59]
C-Panel hat gewarnt, dass der verfügbare Speicherplatz knapp wird. Der Großteil davon wird durch die Mail-Accounts belegt, insgesamt 11,3 von 15,6 genutztem Speicherplatz. Insgesamt sind 19,5 verfügbar, es ist also noch etwas Luft. Aber vielleicht kann bei einigen Postfächern mal aufgeräumt werden oder z.B. Mails gelöscht, die älter als 3 Jahre sind. Accounts mit über einem GB an Daten sind Isabelle Bartram, Judith Düesberg, Kirsten Achtelik und die Liste. Knapp darunter sind Janina Johannsen und Susanne Schulz. 

Hier die Aufstellung aus dem C-Panel: (die Zahlen sind MB)
gen-ethisches-netzwerk.de | 8252.39 
  | beirat | 221.97 
  | bewerbung | 0.47
  | christof.potthof | 6.90 
  | christoph.schulz | 49.81 
  | foej | 9.23 
  | gen | 606.02 
  | gid | 635.79 
  | info | 9.24 
  | isabelle.bartram | 1035.01 
  | janina.johannsen | 849.77 
  | judith.dueesberg | 1151.42 
  | k.achtelik | 1136.05 
  | liste | 1463.58 
  | newsletter | 7.88 
  | petition | 0.08 
  | shop | 44.13 
  | silvia.gruss | 144.65 
  | spam | 0.00 
  | spenden | 0.15 
  | susanne.schultz | 879.02 
  | verwaltung | 0.00 
  | webmaster | 1.21 

Alternativ kann die Disk quota beim Provider hochgesetzt werden - ich weiß nicht, ob und wieviel das extra kosten würde. 

Was denkst du?

**Comment by ibartram** [comment]
ich sag den anderen sie sollen mal aufräumen :) danke fürs bescheid sagen
