### ISSUE TITLE
2. Menüebene ist komisch

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#60]
Wenn ich eingeloggt bin, dann öffnet sich die 2. Menüebene nicht, sondern ich kann nur auf die erste Ebene klicken. dann öffnet sich die Fehler-Seite.

Wenn ich ausgeloggt bin existiert das Problem nicht. Liegt es an mir oder an der Seite?

**Comment by divanke** [comment]
War bei mir auch so. Ich habe den Cache auf dem Server geleert, jetzt gehts bei mir wieder. Und bei dir?

**Comment by ibartram** [comment]
leider immer noch so, zusätzlich funktioniert auch der slider nicht. hab meinen browser-cache gelöscht in der hoffnung dass das was bringt, aber leider nein :(

**Comment by divanke** [comment]
Kannst du bitte nochmal testen? Bei mir läuft es. Sehr merkwürdig.

**Comment by ibartram** [comment]
es funktioniert wieder!!! danke :)
