### ISSUE TITLE
Formular Presseverteiler

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#61]
Ich habe schon versucht das zu machen aber dachte bevor ich jetzt Stunden damit verbringe kannst du dass ja vielleicht schneller und besser machen.

Wir hätten gerne auf der "Presse" Seite rechts ein Block mit Formular mit dem sich Journalist*innen in den Presseverteiler eintragen können.

Also mit den Feldern zum ausfüllen:
Name 
E-Mail
Medium (oder wie man das nennt, also wofür schreiben sie)
Themeninteressen

und ankreuzen wegen Datenschutz mit Hinweis auf Datenschutzerklärung wie bei den anderen Formularen

Wenn jemand das Formular ausfüllt,  soll der Inhalt an presse@gen-ethisches-netzwerk.de geschickt werden.

Danke!

**Comment by divanke** [comment]
Ich musste mich da auch erst mal reinfuchsen ... Schau mal, ob du so zufrieden bist:
[https://www.gen-ethisches-netzwerk.de/pressemitteilungen](https://www.gen-ethisches-netzwerk.de/pressemitteilungen)
