### ISSUE TITLE
Slider ist seltsam

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#63]
Wenn man - ausgeloggt-  auf der Startseite im Slider immer weiter nach links klickt verschwindet der Slider vollständig. Bei mir uns bei Kolleg*innen.

**Comment by divanke** [comment]
Das war einfach :) 
Aus irgendeinem Grund war bei dem Bild zu dem Artikel "Digitalisierung des Gesundheitssystems" das Kästchen für "Publiziert" nicht markiert. Das habe ich nachgeholt und nun wird es wie die anderen angezeigt.
