### ISSUE TITLE
Warnpopups bei bestimmten Artikeln

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#64]
Wir haben einige alte Artikel auf unserer Webseite entdeckt, die wir inhaltlich problematisch finden. Ist es möglich für einen Artikel ein Warnpopup mit einem Artikel-spezifischen Text nur bei bestimmten Artikeln erscheinen zu lassen? Wenn das geht würd ich dir noch mal den genauen Text und die Artikel-Links schicken, wir stimmen uns gerade noch ab wie es formuliert werden sollte.

**Comment by divanke** [comment]
Ja, das ist möglich. Schick mir gern den Text und die Liste von Artikeln, bei der die Warnung erscheinen soll.

**Comment by ibartram** [comment]
Super, ich schicke dir gleich die Texte für die Popups und die Artikel-Links per Mail.

**Comment by ibartram** [comment]
Danke!! Vermutlich werden wir noch mehr solcher Artikel finden, dann meld ich mich noch mal.

**Comment by ibartram** [comment]
Bie mir wird das Warn-popup leider nicht mehr angezeigt :( Hab es in einem privaten fenster getestet, da sollte es nicht an Cookies liegen oder? Da der Artikel leider sehr häufig aufgerufen wird wär es gut das zu wiederherzustellen.
https://www.gen-ethisches-netzwerk.de/172/im-dunkel-des-labors

**Comment by ibartram** [comment]
PS: Bei dem 2. Artikel taucht das Warn-Popup auch nicht mehr auf https://www.gen-ethisches-netzwerk.de/172/hepatitis-b-impfung-frankreich

**Comment by divanke** [comment]
Die Adresse der beiden Seiten hat sich durch das update gestern offenbar geändert. Jetzt ist das popup wieder da.

**Comment by ibartram** [comment]
danke!
