### ISSUE TITLE
Redaktionsmöglichkeiten begrenzen

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#65]
Ich würde gerne die Redaktionserlaubnis für den User "Corona" auf nur eine Seite begrenzen, und zwar
https://gen-ethisches-netzwerk.de/corona. Geht das?

**Comment by divanke** [comment]
Ich habe für den User Corona eine neue Rolle angelegt, die nur eigene Seiten (also jetzt den Artikel Corona-Chronologie) bearbeiten und löschen darf. Diese Rolle darf auch Dateien und Medien hochladen und eigene Dateien und Medien bearbeiten und löschen. 
Um das Ergebnis zu überprüfen, habe ich das Passwort des Users Corona geändert, bitte setze ein neues!
Schau bitte, ob alles so passt. Falls mehr oder weniger Rechte benötigt werden, sag Bescheid.

**Comment by ibartram** [comment]
danke alle super, nur dass das "publishing status" -Häkchen verschwunden ist und damit die Möglichkeit das ganze für alle sichtbar online zu stellen... Könntest du das noch kurz ändern, die Seite soll eigentlich morgen online gehen. Danke!!!

**Comment by ibartram** [comment]
könntest du bitte die redaktionsmöglichkeiten für den Corona-Account auf eine 2. Seite ausdehnen? nähmlich: /corona-lockdown
Danke!

**Comment by divanke** [comment]
Ich habe bei dem Artikel Corona-Lockdown statt deiner jetzt Corona als Autor*in eingetragen, damit hat Corona für diesen Artikel jetzt auch die Redaktionsmöglichkeiten wie für das Corona-Tagebuch.

**Comment by ibartram** [comment]
vielen Dank!
