### ISSUE TITLE
Automatische Umleitung

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#66]
Ich habe einen Post angelegt, damit die Corona-Seite im Slider beworben wird, allerdings ist der Artikel selber ziemlich redundant, da er als eizige Info den Link zu der Seite anthält. Daher meine Frage ob es eine Automatische Umleitung von der 
URL
https://gen-ethisches-netzwerk.de/april-2020/die-coronakrise
zu
https://gen-ethisches-netzwerk.de/corona
geben könnte?

**Comment by divanke** [comment]
Ja, sorry, der dummy-Artikel war von mir, habe ihn wieder gelöscht ... entschuldige den Fehler. 
Ich habe keine einfache Möglichkeit gefunden, eine automatische Umleitung zu erstellen. 
Wäre es nicht sinnvoller, statt einer Seite einen Online-Artikel aus dem Corona-Tagebuch zu machen? Dort gibt es ja die Möglichkeit, den Artikel auf der Startseite zu promoten.
