### ISSUE TITLE
Benutzer löschen?

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#67]
Eine Frage: Kann ich Benutzer löschen ohne dass die von Ihnen erstellten Artikel in irgendeiner Form verändert werden? Ich möchte es lieber nicht testen...

**Comment by divanke** [comment]
Wenn du ein Benutzerkonto löschen willst, bekommst du zuerst diese Auswahl angezeigt:

Beim Aufheben dieser Benutzerkonten:
- Das Benutzerkonto deaktivieren und damit erstellten Inhalt behalten.
- Das Benutzerkonto deaktivieren und die Veröffentlichung des damit erstellen Inhalts zurücknehmen.
- Das Benutzerkonto löschen und dessen Inhalt dem Benutzer . zuordnen.
- Das Benutzerkonto und dessen erstellten Inhalt löschen.

Wenn du die dritte Option wählst, bleibt der Inhalt des Artikels und auch der/die auf der Website angezeigte Autor*in erhalten, nur bei der Content-Liste im Backend erscheint dann unter AUTHOR ". (nicht überprüft)". Die Benutzer*innen sind unabhängig von den Autor*innen der Artikel.
