### ISSUE TITLE
Abgesetzer Text durch graue Unterlegung?

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#68]
Ich wurde folgendes gefragt, vielleicht hast du eine Lösung?

Ein Textkasten mitten im Text auf einer Seite, "Kasten" meint es wäre schön, wenn wir das mit hellgrau unterlegen oder sonst irgendwie absetzen könnten vom restlichen Text. 

Was mir dazu einfällt wäre einen neuen Typ Überschrift anzulegen der den Text grau unterlegt? Oder kann man irgendwei ein Kästchen anlegen mit einer bestimmten Hintergrundsfarbe?

**Comment by divanke** [comment]
Es gibt jetzt ein weiteres Feld im Editor, es heißt Stile und enthält den Stil Textbox. Die Veränderung (also die graue Hinterlegung) im Text wird im Editor nicht angezeigt, aber unten im Editorrand steht 'div box', wenn man mit dem curser im betreffenden Absatz steht. Zum nächsten Absatz (also raus aus der Textbox) kommt man, wenn man auf das rote 'Enter'-Symbol klickt, das erscheint, wenn man mit der Maus den Rand des Kastens überstreicht. 
Ist das so passend bzw. entspricht euren Wünschen?
