### ISSUE TITLE
Shop - Infopost & Newsletter

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#69]
Es gibt im Shop bei der Anmeldung die Möglichkeit zu sagen man möchte den Newsletter bekomme. Ich weiß nicht genau wie das jetzt aussieht, aber könntest du das ergänzen

Einmal soll nicht nur Newsletter da stehen sondern "E-Mail-Newsletter: 1x im Monat relevante Meldungen aus Wissenschaft und Politik sowie Informationen zu unserer Arbeit - jederzeit abbestellbar. mehr Informationen" und das "mehr Informationen mit https://www.gen-ethisches-netzwerk.de/newsletter verlinken

Und dann hätten wir gerne noch einen zweite Möglichkeit ein Häkchen zu setzen:
"kostenlose GeN-Infopost: 4 bis 6x im Jahr Informationen zu aktuellen Aktionen, politischen Entwicklungen und unserer Arbeit - jederzeit abbestellbar."

 Danke!

**Comment by divanke** [comment]
Ich habe den Text beim Häkchen geändert, allerdings kann ich dort kein html einfügen und habe des halb "Mehr Informationen"/den Link weggelassen. Wenn der Text geändert werden soll: das geht im prestashop backend bei Lokalisierung->Übersetzungen.
Das zweite Häkchen ist hinzugefügt. Wenn ein neues Kund*innenkonto angelegt wird, sieht man im backend, dass die Person die Info-Post möchte, wenn bei "Opt-in" ein Häkchen ist. Ist das so brauchbar für euch? Auch dieser Text ist wie oben beschrieben änderbar.

**Comment by ibartram** [comment]
Das ist super so, Danke!
