### ISSUE TITLE
Optionen für zeitgesteuerte Veröffentlichung

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#70]
Meine Kollegin stellt einen Teil der GID-Artikel immer so ein, dass sie nach ein paar Monaten online gehen. Bei diesem einen Artikel wollten wir das jetzt ausnahmsweise rückgängig machen. Es geht aber nicht. Die eingestellte Zeit steht bei --:--:--, auch wenn man es ändert und speichert, der Artikel ist wenn man eingeloggt ist lesbar aber nicht wenn man sich ausloggt. das rote Kästchen was sonst auf der GID-Seite nicht freigeschaltete Artikel markiert ist weg. Woran liegt das?? Wie krigen wir den Artikel freigeschaltet? Es geht um diesen hier
https://www.gen-ethisches-netzwerk.de/agrobusiness/wissenschaftskritik/252/aufgedeckt-monsantos-versteckte-finanzierung

**Comment by ibartram** [comment]
PS: meine kollegin hat jetzt heute nacht als veröffentlichungsdatum angegeben und hofft das es funktioniert warum auch immer...

**Comment by divanke** [comment]
Hat offenbar funktioniert ... ist der workaround, den ihr gefunden habt okay, oder soll ich da genauer reinschauen?
