### ISSUE TITLE
DGSVO-Popup kaputt

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#71]
Bei mir und meinen Kolleg*innen wird das DGSVO-Popup seit neustem fehlerhaft angezeigt. Der Text fehlt, statt dessen gibts nur die 2 buttons mit "Ok" und "mehr informationen" oder so. Könntets du das bitte reparieren? danke!

**Comment by divanke** [comment]
Das scheint an einer schlechten Zusammenarbeit zwischen dem Matomo-Opt-out-Plugin und dem Drupal-Modul zu liegen. Ich habe jetzt eine ältere Version des Moduls installiert, bei der es funktioniert. Sollte so erstmal okay sein.

**Comment by ibartram** [comment]
super, danke!
