### ISSUE TITLE
leerzeichen nach Links

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#72]
Wenn man Links einbaut gibt es immer so ein Leerzeichen danach plus so ein kleines Zeichen von dem ich nicht weiß wozu das gut ist,a ebr vl hat es eine Funktion/Bedeutung. Könntest du das so ändern, dass zumindest das Leerzeichen weg ist?

**Comment by divanke** [comment]
Das Zeichen zeigt an, dass der link auf eine externe Seite verweist und sich in einem neuen Tab öffnet. Ich kann das Symbol einfach entfernen - das Leerzeichen sehe ich in meinem Browser nicht ...
