### ISSUE TITLE
Vorlese-Tool

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#73]
Wir haben das Angebot bekommen für 20 Euro im Jahr ein Vorlese-Tool für die Webseite zu installieren um die barrierefreiheit zu erhöhen,. Die frage ist ließe sich das überhaupt bei uns installieren und denkst du es ist sinnvoll? Es heißt ReadSpeaker Webreader

**Comment by divanke** [comment]
Es gibt ein drupal modul, das open readspeaker heißt und mit dem das Tool offenbar eingebunden werden kann. Testen kann ich es nur mit einem Account bei ReadSpeaker. Ich kann also nicht definitiv sagen, wie reibungslos die Implementierung ist, aber ich denke, es sollte gehen. Und zur Erhöhung der Barrierefreiheit bin ich etwas unsicher: Wenn ich das richtig verstehe, liest readspeaker einzelne Artikel vor. im Gegensatz dazu liest ein Screenreader die ganze Website mit Header, Menü etc. Ich vermute, (z.B. blinde) Menschen, die auf Screenreader angewiesen sind, haben welche, die für alle Textinhalte (also auch für die Website des GeN) funktionieren. Für Menschen mit Leseschwäche könnte ReadSpeaker sinnvoll sein: für die Struktur der Website genügen die Lesekompetenzen, längere Artikel können sie sich vorlesen lassen. 
Ob ihr das für eure Seite sonnvoll haltet, müsst ihr entscheiden, denke ich. Ich bin ein bisschen skeptisch, könnte aber einen Freund fragen, der blind ist, was er dazu denkt. Melde dich gern, wenn du denkst, das macht Sinn.
