### ISSUE TITLE
neue Themenseite

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#74]
ich möchte eine neue Themenseite zu Corona anlegen aber weiß nicht wie es geht.
Also eine Seite wie https://www.gen-ethisches-netzwerk.de/biopolitik-und-bioethik/wissenschaftskritik, mit einem Einleitungstext und dann die Auflistung von "Beiträge zu diesem Thema" darunter. Den Infokasten rechts kann ich selbst anlegen. Dann muss es auch ein neues Thema "Corona" geben mit dem ich die Artikel (auch die jetzt schon existenten) zum Thema einsortieren kann.
Danke!

**Comment by divanke** [comment]
Dein user hat die Berechtigung nicht, ein neues Thema anzulegen. Ich habe das jetzt gemacht, du kannst es bearbeiten unter Struktur -> Taxonomie -> Themen
Dann kannst du Artikel diesem Thema zuordnen und den Link im Menü, wo jetzt das Corona-Tagebuch verlinkt ist, ersetzen durch einen Link zum neuen Thema. Das Corona-Tagebuch ist wieder ein Sonderfall, weil es als Seite und nicht als Arikel angelegt ist, deshalb kann ihm kein Thema zugeordnet werden. Falls du keine Lösung dafür findest, gib mir gern Bescheid.

**Comment by divanke** [comment]
Soll ich hier mal den Anfang machen? Oder war meine Erläuterung des Vorgehens nicht konkret genug? Noch zeigt der Link im Menü nur auf das Tagebuch - jetzt wo das neue Heft zum Thema online ist, macht deine Idee mit der Themenseite total Sinn, wäre gut, das bald umzusetzen.

**Comment by ibartram** [comment]
Danke aber bin einfach noch nicht dazu gekommen, weil ich noch den Text für die Seite schreiben und mit den anderen abstimmen muss. Das Corona-tagebuch würde ich in diesem Einführungstext verlinken. Ich setz mich da nächte Woche dran und würd mich melden falls Probleme auftauchen

**Comment by ibartram** [comment]
so es hat geklappt, nur steht unten "Artikel und Analysen zu Covid-19" - ich kann es leider nicht entfernen, könntest du das machen?

**Comment by divanke** [comment]
Ist geschehen :)

**Comment by ibartram** [comment]
danke!!
