### ISSUE TITLE
Slider-Probleme

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#75]
Nur wenn man nicht eingeloggt ist, verschwindet der Slider wenn es vom ersten Bild zum 2. umschalten sollte. Woran kann das liegen? Wenn man eingeloggt ist gibt es keine Probleme.

**Comment by divanke** [comment]
Gleiches Problem wie bei "Slider ist seltsam #63": das zum Artikel gehörige Bild war nicht als publiziert markiert. Ist jetzt behoben.

**Comment by ibartram** [comment]
vielen Dank, aber wie kommt es dazu dass das Bild nicht als publiziert markiert war? Seltsam.

**Comment by divanke** [comment]
Kann ich nicht sagen. Voreingestellt ist, dass das Bild publiziert wird. Ich vermute ein Versehen der Person, die den Artikel erstellt hat.
