### ISSUE TITLE
Jahreszahlen Pressemitteilungen

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#76]
Uns ist aufgefallen, dass bei den Pressemitteilungen das Drop-down Menü für die jahreszahlen nur bis 2018 geht, könntest du das bitte aktualisieren? Danke!

**Comment by divanke** [comment]
Oh ja, sorry, das hatte ich wohl übersehen... ist geschehen! (ich mach mir ne Erinnerung, dass ich das im Januar für 2021 mache ...)

**Comment by ibartram** [comment]
Liebe Anke, 2021 fehlt jetzt leider, magst du das noch hinzufügen? Danke!

**Comment by gengid** [comment]
Hallo Isabelle,

Danke, ich habe mir für nächstes Jahr eine Erinnerung geschrieben - das
muss jedes Jahr per Hand ergänzt werden ...

Liebe Grüße,

Anke


Am 18.05.21 um 12:21 schrieb ibartram:
> Liebe Anke, 2021 fehlt jetzt leider, magst du das noch hinzufügen? Danke!
>
