### ISSUE TITLE
Unterstützer*innen neu

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#77]
Wir möchten gerne auf der Unterstützer*innen-Seite die Stiftungen die uns fördern auflisten, aber irgendwie separat von den Personen. Vorschlag war eine rechte separate Randspalte anzulegen, also wie bei Artikeln, und oben steht "Wir werden außerdem unterstützt von:" und dann die Logos und ein kleiner Text jeweils.

**Comment by divanke** [comment]
Ich habe die Randspalte erstellt, aber erst mal nur für eingeloggte Betrachter*innen sichtbar gemacht. Wenn ihr die Stiftungen eingetragen habt, gebt mir bescheid, dann würde ich das für alle sichtbar machen und dann auch die Anzahl der Unterstützer*innen links auf drei reduzieren, damit die Bilder nicht so klein werden und die Zitate komplett sichtbar sind. 
Eintragen könnt ihr die Stiftungen unter:
Blöcke -> Bibliothek benutzerdefinierter Blöcke -> Liste der fördernden Stiftungen -> Bearbeiten

Wenn es da Probleme gibt meldet euch gern. Ihr könnt mir auch Logos und Texte schicken, dann kann ich das machen.

**Comment by Theresa-GeN** [comment]
Hallo Anke,

hier ist Theresa Roy, Isabelle Bartrams Vertretung. Ich hatte Ihnen gerade eine Mail geschickt und füge mein Anliegen hier nochmal ein.

Es geht um den neuen Unterstützer*innen-Kasten für die Stiftungen. Ich kann ihn zwar eingeloggt sehen aber weder ich noch Janina können ihn bearbeiten (keine Berechtigung). Können Sie das ändern?

Auf eine gute Zusammenarbeit und viele Grüße

Theresa Roy

**Comment by divanke** [comment]
Hallo Theresa, 

tut mir leid, der content des Blocks war in "full html", wofür ihr keine Bearbeitungsberechtigung habt ... Jetzt ist es "Einfaches html", das genügt, und ihr könnt es bearbeiten :)

Liebe Grüße, 

Anke

**Comment by Theresa-GeN** [comment]
Hallo Anke, 
vielen vielen Dank, das ging ja superschnell gestern! Wir können uns übrigens sehr gern Dutzen.
Bis auf ein fehlendes Logo steht unser Kasten nun soweit aber ich habe ein neues Problemchen. 
Ich hab jetzt immer abwechselnd ein Logo und darunter einen Satz in dem Kasten. Jedesmal, wenn ich ihn bearbeite und dann speichere, fügt sich unter jedem Bild eine zusätzliche Leerzeile ein. Wenn ich wieder bearbeite und die Zeilen entferne, sind sie nach dem Speichern wieder da. Wenn ich sie nicht entferne, sind nach dem Speichern unter jedem Bild schon zwei Leerzeilen usw. 
Habe die Sätze als Bilduntertitel angebunden und horizontale Linien eingefügt, das hat aber nichts an diesem "Verhalten" geändert. 
Kenne mich leider gar nicht mit Websites aus, kann man da was tun?
Liebe Grüße Theresa

**Comment by Theresa-GeN** [comment]
PS: Das letzte Logo ist da, der Kasten kann sichtbar gemacht werden.

**Comment by divanke** [comment]
Ich habe es veröffentlicht. Das mit den Leerzeilen hatte sich dann doch irgendwie geklärt? Ich seh es zumindest nicht mehr.

**Comment by Theresa-GeN** [comment]
Danke, der Kasten sieht so gut aus. Die Leerzeilen, die er dort selbstständig einfügt hat, passen ganz gut hin.
Ich sag einfach Bescheid, falls das nochmal an einer anderen Stelle auftritt.
Schönes Wochenende!
