### ISSUE TITLE
Upload von Audiodateien

### ISSUE THREAD

**Issue by Theresa-GeN** [gengid/ticket#78]
Liebe Anke,

seit einer Weile arbeiten wir an einem Podcast-Projekt. Wir möchten dafür von uns produzierte Audiodateien im mp3-Format (10-20 min Länge) auf unsere neue Seite laden: https://www.gen-ethisches-netzwerk.de/podcast

Im Backend konnte ich keine Möglichkeit finden, Audios hochzuladen oder auf einer bestimmten Seite einzustellen. Habe ich da etwas übersehen? Falls nicht, wäre es möglich, soetwas für unsere Page einzurichten? Könntest du das übernehmen?

Liebe Grüße, Theresa

**Comment by divanke** [comment]
Hallo Theresa, 

ich habe einen neuen Content-Type Audio erstellt, über den ihr die Dateien hochladen könnt. Den Inhaltstyp Seite habe ich um eine Möglichkeit erweitert, Audio einzubinden. Schau doch mal rein, ob es so passt. Die Dateigröße ist auf 8 MB begrenzt - reicht das?

**Comment by Theresa-GeN** [comment]
Hallo Anke,
cool, vielen Dank! Das sieht doch schonmal supi aus. Ich hätte mal gleich nachschauen sollen, die erste Podcast-Folge ist 34 MB groß. Kann man die Begrenzung auf 40 oder 50 MB erhöhen?
Danke dir, Theresa:)

**Comment by divanke** [comment]
Ich vermute, die Begrenzung liegt nicht in meinem Einflussbereich. Wenn ich im cpanel die erlaubte Größe nach oben schraube, ändert sich nichts im backend. Ich habe eine Supportanfrage an den Hoster, Dennis von planetary networks, geschickt, der sollte das auch auf dem Server ändern können.

**Comment by divanke** [comment]
Jetzt können auch Dateien bis 50 MB hochgeladen werden.

**Comment by Theresa-GeN** [comment]
Vielen Dank!
