### ISSUE TITLE
Podcast-Seite

### ISSUE THREAD

**Issue by Theresa-GeN** [gengid/ticket#79]
Liebe Anke,

für unser Podcast-Projekt haben wir eine neue Seite erstellt und auch schon die erste Audiodatei hochgeladen. Jetzt gibt es ein paar Layout-Probleme, die ich nicht lösen kann.

https://www.gen-ethisches-netzwerk.de/podcast

1. Neben und unter der Audiodatei sind die Bezeichnungen "gen-podcast_folge_1.mp3" und "Folge_1" sichtbar. Können diese beiden Schriftzüge entfernt werden?
2. Zur Audiodatei soll es ein kleines Bild geben, das links NEBEN der Datei sichbar ist und eben kleiner ist, als z.B. das große Bild oben auf der Seite. Kannst du das einrichten oder mir sagen, wie ich das hinkriege?
3. Wie kann ich auf der Podcast-Seite rechts einen Kasten installieren bzw. kannst du dort einen hinpacken? Er soll die Informationen beinhalten, die aktuell noch in der Fußnote der Seite liegen. Diese Blöcke-Struktur im Backend versteh ich ja nicht so recht...

Vielen Dank und Liebe Grüße

Theresa

**Comment by divanke** [comment]
Hallo Theresa, 

die Bezeichnungen habe ich entfernt und die Info zum Podcast in einen Kasten rechts eingefügt (bei Blöcke einen neuen benutzerdefinierten Info-Block anlegen, ihn im Block-Layout bei secondary einfügen und auf die Podcast-Seite beschränken - ich bin mir aber gar nicht sicher, ob du dafür alle notwendigen Berechtigungen hättest ... meld dich in jedem Fall gern bei mir, wenn was nicht geht!).

Ich habe die Audiodateien jetzt so eingestellt, dass direkt dazu ein Bild hochgeladen werden kann (ich habe jetzt einen kleinen Platzhalter erstellt, den du bei der Podcast-Datei in content->media durch euer Bild ersetzen kannst). Das Bild darf maximal 600x600 px und 2MB groß sein. Angezeigt wird es jetzt in 100x100px. Wenn es größer angezeigt werden soll, gibt mir Bescheid und sag mir die ungefähre Größe & Proportionen, dann ändere ich das. 

Liebe Grüße, 

Anke

**Comment by Theresa-GeN** [comment]
Vielen Dank, liebe Anke!
Ich kann den Kasten aber, wie du sagts, leider nicht bearbeiten. Andere Kästen kann ich schon bearbeiten. Kannst du mir die Berechtigung dafür denn geben? 
Es gibt im Moment aber erstmal keine konkreten Änderungen.

LG Theresa

**Comment by divanke** [comment]
Sorry, jetzt gehts. Es war das falsche Textformat ausgewählt.

**Comment by Theresa-GeN** [comment]
Hallo Anke,

hier gleich noch eine Post von uns. Meine Kollegin möchte den neuen GeN-Podcast weiter einrichten und hat dazu eine Frage, die ich selbst nicht ganz verstehe, dir aber hoffentlich etwas mehr sagt?

"Es geht um das Hosting unseres Podcasts. Die Frage ist, ob es sich für uns anbieten würde, die Folgen auf unserer Webseite zu hosten und von dort den RSS-Feed händisch an Spotify und co einzureichen - ich habe gelesen, dass das regelmäßigen Abgleich mit Updates bei Wordpress und co erfordert."
Hälst du das in unserem Fall für machbar?

Liebe Grüße aus dem GeN

Theresa

**Comment by Piavoelker** [comment]
Liebe Anke, 
wir hosten unseren Podcast über Podigee. Ich würde gern den Webplayer von Podigee auf unserer Webseite unter https://www.gen-ethisches-netzwerk.de/podcast einbetten. 

Es wird regelmäßig neue Folgen geben. Gibt es eine Möglichkeit, dass die neuen Folgen automatisch im Webplayer auf unserer Webseite erscheint? Oder müssen die alle einzeln eingebettet werden?

Und: soll ich den Code für den Webplayer hier posten? Oder auf einem anderen Kanal? 
Liebe Grüße, Pia vom GeN

**Comment by divanke** [comment]
Hallo Pia,

tut mir lied, dass ich dich so lange warten lasse. Ich werde mich am
Wochenende oder spätestens am Montag damit beschäftigen - es ist so viel
zu tun gerade! Aber es gibt offenbar ein Modul, über das Podigee auf der
Seite eingebettet werden kann. Ich teste das aus und melde mich wieder
bei dir.

Liebe Grüße,

Anke

Am 23.03.21 um 12:04 schrieb Piavoelker:

**Comment by Piavoelker** [comment]
Liebe Anke, 
es gibt so ein Modul, ich habe hier auch den Code dafür in meinem Podigee-Account gefunden. 
Lass mich gern wissen was du von mir dafür brauchst. 
Liebe Grüße und vielen Dank dir, Pia

**Comment by divanke** [comment]
Hallo Pia,

mit Modul meinte ich die  Einbindung über drupal - aber schick mir gern,
was du im Podigee account gefunden hast. Kannst du mir auch Zugang zum
Podigee-Account des GeN geben - zumindest temporär? Das macht es mir
möglich oder leichter, den Account und die dort gehosteten Folgen mit
der Website zu verbinden.

Liebe Grüße,

Anke

Am 25.03.21 um 10:46 schrieb Pia Voelker (GeN):
