### ISSUE TITLE
Format Text vs. Bild

### ISSUE THREAD

**Issue by Theresa-GeN** [gengid/ticket#80]
Liebe Anke, 

wir haben gerade eine neue Page im Aufbau, auf der wir unseren neuen Flyer präsentieren. Das Cover des Flyers ist auch schon als Bild eingebaut.
https://gen-ethisches-netzwerk.de/corona-impfstoffe

Da das Bild so lang und schmal ist, würden wir einen Teil des Website-Textes gern daneben setzen, statt ihn unter dem Bild zu haben.

Im Bearbeitungsmodus der Website lässt er mich das  Bild zwar als linksbündig einstellen und zeigt den Website-Text dann auch rechts daneben an, das hat aber leider keine Auswirkungen auf die Darstellung der Website.  Kannst du mir da vielleicht helfen?

Liebe Grüße

Theresa

**Comment by divanke** [comment]
Hallo Theresa, 

ich hab es jetzt mal so eingerichtet - falls ihr das öfter braucht, sag nochmal Bescheid, dann bemühe ich mich, eine generelle Lösung zu finden, die auch für euch funktioniert. Diese war jetzt etwas frickelig und nur mit Admin-Rechten möglich. 

Liebe Grüße, 
Anke

**Comment by divanke** [comment]
So, jetzt habe ich es sauberer gelöst. Sollte jetzt generell funktionieren.

**Comment by Theresa-GeN** [comment]
Hallo Anke,

ich war eine Weile im Urlaub. Vielen Dank für das Format! :)

LG Theresa
