### ISSUE TITLE
Glossar für die Website

### ISSUE THREAD

**Issue by Theresa-GeN** [gengid/ticket#81]
Liebe Anke,

wir haben uns im Büro über die Zukunft unserer Website unterhalten und viele Ideen gesammelt, die man vielleicht mal irgendwie umsetzten kann. Eine Idee ist das Anlegen eines Glossars, der dem User häufige (Fach-)Begriffe kurz erklärt.

Am sinnvollsten wäre das natürlich, wenn die fraglichen Begriffe direkt in unseren Artikeln mit der Information des Glossars verknüpft sind. Das klingt allerdings recht aufwändig, händisch alle Glossarbegriffe abzuklappern und beim Upload eines Artikels einzeln zu verlinken. 

Deswegen eine hypothetische Frage: Wäre es technisch möglich (und uns/dir zugänglich), die Website dazu zu bringen, dass sie Glossarbegriffe automatisch erkennt und mit der entsprechenden Info verknüpft (z.B. als Tooltip anzeigt oder eine Verlinkung zu einer entsprechenden Glossarseite erstellt)?

Und wenn ja, welche Nachteile hätte die Umsetzung? Würde uns diese Möglichkeit z.B. laufende Kosten bescheren oder die Kapazität der Website stark ausreizen?

Viele liebe Grüße

Theresa

**Comment by divanke** [comment]
Hallo Theresa,

ich habe ein Modul installiert, was diese Glossarfunktion bereitstellt.
Unter Struktur->Taxonomie->Glossar könnt ihr Begriffe eintragen und
erläutern. Diese Begriffe werden dann in allen Texten, die das
Textformat "einfaches HTML" haben, gestrichtelt unterstrichen und es
wird beim Überfahren mit der Maus ein Tooltip, eine kleine Box
angezeigt, in der die Erläuterung steht. Der Begriff wird nur beim
ersten Vorkommen markiert - das kann aber auch geändert werden. Das
Textformat "einfaches HTML" ist das Textformat, in dem die Fließtexte
der Online- und GiD-Artikel geschrieben sind. Probiert gern mal aus, ob
das so für euch passt oder ob noch etwas geändert werden soll, und dann
schaue ich, was sich machen lässt ;)

Liebe Grüße,

Anke

Am 04.03.21 um 14:42 schrieb Theresa-GeN:

**Comment by Theresa-GeN** [comment]
Hey Anke, 
vielen Dank für dieses praktische Modul! Was die Technik nicht alles leisten kann :D 
Wir probieren es aus, ich melde mich, falls es Änderungswünsche gibt.
Viele liebe Grüße 
Theresa

**Comment by ibartram** [comment]
Hallo, es gab die Frage zum Gloassar ob es möglich wöre einzustellen, dass die Glossar-Begriffe nur auf bestimmten Seiten, oder bei bestimmten Artikeltypen markiert werden. Also zum Beispiel nicht auf der Seite /ueber-uns aber bei allen gid-artikeln.

**Comment by divanke** [comment]
Hallo Isabelle, 
das Glossify-Modul hat dafür keine Einstellmöglichkeiten. Wenn es bei einzelnen Seiten oder in bestimmten Bereichen (z.B. Überschriften oder Seitenkasten) stört, kann ich es "per Hand" über das CSS für diese Stellen eventuell ausblenden. Für genauere Angaben dazu müsste ich wissen, an welche Stellen ihr denkt, wo es nicht angezeigt werden sollte. 
Liebe Grüße, 
Anke

**Comment by ibartram** [comment]
Irgendwas läuft mit dem Glossar grad falsch :(
Hier z.B.: GeGenome EditingGentests, https://www.gen-ethisches-netzwerk.de/mitarbeiterinnen

**Comment by divanke** [comment]
Hallo Isabelle, das ist ein bug im modul, hat vermutlich etwas mit umlauten/Sonderzeichen zu tun ... ich hoffe, dass es bald gefixt wird - ich glaube nicht, dass ich das selbst fixen kann. Soll ich es so lange deaktivieren? Dann werden die Erklärungen nicht angezeigt, aber auch nicht die Wörter zerhackt.

**Comment by divanke** [comment]
Ah, oder ich kann später mal auf eine ältere Version wechseln und schauen, ob es dort auch auftritt.

**Comment by ibartram** [comment]
Danke, hat funktioniert :)

**Comment by ibartram** [comment]
Du sag mal, könnte man irgendwie die Glossarfunktion selektiv für bestimmte Seiten/Artikel abschalten? vl mit dem Häkchen beim erstellen des Artikels? Bei englischen Texten ergeben die Glossartexte leider z.T. gar keinen Sinn, es wirkt dasnn so unprofessionell. Ich will vermehrt auch Pressemitteilungen übersetzen um größere Zielgruppen zu erreichen. zb. https://www.gen-ethisches-netzwerk.de/Gene-SOEP#english

**Comment by divanke** [comment]
Hallo Isabelle, für dein genanntes Beispiel ist das möglich. Die Glossar-Einträge haben eine zugeordnete Sprache. Wenn ein Artikel die gleiche zugeordnete Sprache hat, werden die Glossar-Begriffe angezeigt. Wenn der Artikel einer anderen Sprache zugeordnet ist, werden die Begriffe nicht angezeigt. Bislag wurden aller Content und alle Glossar-Einträge automatisch in der Standardsprache der Website (German) abgelegt. Ich habe jetzt bei den Content-Types Seite und Online-Artikel eine Auswahlmöglichkeit für Sprache hinzugefügt. Bei der English-Seite, die oben im Extra-Menü verlinkt ist, habe ich das jetzt genutzt und die Sprache auf Englisch umgestellt, jetzt werden hier die Glossareinträge nicht mehr angezeigt. Wenn du einzelne Artikel auf Englisch übersetzen möchtest, wäre es sinnvoll, wenn du ein Dokument für die Deutsche und ein Dokument für die Englische Version benutzt und die jeweils andere dann im Dokument verlinkst, damit die beiden jeweils der richtigen Sprache zugeordnet werden. Das erleichtert eventuell auch eine spätere Einführung von Zweisprachigkeit ... Damit habe ich mich aber noch nicht näher beschäftigt. 
Hilft das erst mal weiter?
