### ISSUE TITLE
Anzeige von Untertiteln

### ISSUE THREAD

**Issue by Theresa-GeN** [gengid/ticket#82]
Liebe Anke,

wir haben folgenden Wunsch beschlossen, könntest du das umsetzen?

Wenn man einen GID-Artikeln aufruft, wird unter dem Titel auch sein Untertitel angezeigt, z.B. hier:
https://gen-ethisches-netzwerk.de/reprotechnologien/256/von-leitlinien-und-liebe-samen-und-sorgen

Bei Online-Artikeln hingegen erscheint der Untertitel nur im Slider und nicht über dem Artikel, z.B. hier:
https://gen-ethisches-netzwerk.de/november-2020/schnell-aber-sicher

Wir wünschen uns, dass die Untertitel der Online-Artikel ebenfalls angezeigt werden, wie die Titel der GID-Artikel. Allerdings soll das NICHT der Fall sein, wenn der Online-Artikel als Pressemitteilung oder Stellungnahme gekennzeichnet ist, z.B. hier:
https://gen-ethisches-netzwerk.de/pressemitteilungen/maerz-2021/tanz-am-abgrund

In diesem Fall soll wie gehabt der Untertitel nur im Slider erscheinen. Ist diese Unterschiedung möglich?

Liebe Grüße

Theresa

**Comment by divanke** [comment]
Hallo Theresa, 

es war etwas mühsam, einen Weg zu finden, ist jetzt aber so wie gewünscht. 

Liebe Grüße!

**Comment by Theresa-GeN** [comment]
Hey Anke,

super, dass du es hinbekommen hast! 

Vielen lieben Dank
