### ISSUE TITLE
Komische Markierung

### ISSUE THREAD

**Issue by Theresa-GeN** [gengid/ticket#83]
Hallo Anke,

wir haben entdeckt, dass sich die Textzeile "id>" an verschiedenen Stellen der Website eingeschlichen hat, z.B. unter dem Titel auf den Themenseiten oder über den Sucherergebnissen, wenn ich nach einzelnen Autor*innen suche oder auch z.B. bei "Publikationen" unter der Zeile "Unsere Ausgaben".

https://gen-ethisches-netzwerk.de/agro-gentechnik
https://gen-ethisches-netzwerk.de/christof-potthof
https://gen-ethisches-netzwerk.de/publikationen/gid

Ich weiß nicht, wie sie dort gelandet ist, aber könntest du sie wieder entfernen?

Vielen Dank und liebe Grüße

Theresa

**Comment by divanke** [comment]
Hallo Theresa, 

ich habe zugegebenermaßen keine Idee, wie das dort gelandet ist. Aber ich habe (hoffentlich) alle Vorkommen aufgespürt und entfernt. Merkwürdig ...

**Comment by Theresa-GeN** [comment]
Supi, danke!

**Comment by Theresa-GeN** [comment]
Liebe Anke,

jetzt ist auf der Spenden-Seite etwas verrutscht: https://gen-ethisches-netzwerk.de/spenden

Diese mit der GLS-Bank verknüpfte Bezahl-Einbettung mit dem Herzchen-Regler ist nach unten gewandert. Sie sollte eigentlich unter dem ersten Absatz und über dem Satz "Oder überweisen Sie uns..." zu sehen sein.

Kannst du das wieder zurückschrauben?

Ich hoffe, du hattest schöne Ostertage:) 

Viele Grüße Theresa

**Comment by Theresa-GeN** [comment]
Danke dir!
