### ISSUE TITLE
Neue Artikel-Kategorie

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#85]
Liebe Anke, 
wir brauchen neben "In anderen Medien" und "Pressemittelung" nun auch noch die Kategorie "Presseerwähnung", magst du das als Anklick-Option dazutun? Verlinken im Menü schaff ich dann hoffentlich allein.. 
Danke!
LG, Isabelle

**Comment by divanke** [comment]
Hallo Isabelle, 
ich hab die neue Kategorie eingefügt, verfügbar bei Onlineartikeln. Meld dich gern, wenn noch was zu tun ist!
Anke

**Comment by ibartram** [comment]
Danke! Klappt die Sachen einzusortieren, aber jetzt gibt es unter https://www.gen-ethisches-netzwerk.de/presseerwaehnung den selben Aufbau wie bei Presseerklärungen. Gerne einen neuen Text und kein DRop down menü oder sowas

"Hier finden Sie Berichte über unsere Arbeit in der Presse."

**Comment by divanke** [comment]
Hallo Isabelle,

passt das so?
https://www.gen-ethisches-netzwerk.de/presseerwaehnung
Mit dropdown meintest du die Auswahl der Jahre, richtig? Das können wir
nachträglich einbauen, wenn das erste Jahr vorüber ist oder so.

Liebe Grüße,

Anke

Am 18.05.21 um 14:09 schrieb ibartram:
> Danke! Klappt die Sachen einzusortieren, aber jetzt gibt es unter https://www.gen-ethisches-netzwerk.de/presseerwaehnung den selben Aufbau wie bei Presseerklärungen. Gerne einen neuen Text und kein DRop down menü oder sowas
> 
> "Hier finden Sie Berichte über unsere Arbeit in der Presse."
>

**Comment by ibartram** [comment]
Ja super! Danke! Wo im Backend könnte ich den Text ggf. selber noch mal ändern? oder fehlen mir dazu die Rechte? Ich meine das "Hier finden Sie Berichte über unsere Arbeit in der Presse."

**Comment by ibartram** [comment]
Könnten du bistte bei /andere-medien auch das drop-down-menü entfernen und den Text ändern in (bzw. hier auch die Frage wo ich das selber ändern kann)

"Artikel und andere Publikationen von Mitarbeiter*innen des Gen-ethischen Netzwerks in anderen Medien ab Februar 2017. Erwähnungen unserer Arbeit in der Presse finden Sie hier." (und da verlinkt die Presseerwähnungen)

**Comment by ibartram** [comment]
Ja, vielleicht könnte man die Rollen auch umbenennen so dass der Titel eindeutiger ist und die mit mehr Rechten nur 2 Leute geben? Also Redaktionsadministration (nur ich und Janina) und Redakteur*in alle anderen? Vielleicht könntest du mir nochmal sagen mit welcher Rolle man was darf? Ich hab den Überblick verloren, dachte die eine Rolle wäre ausreichend um Redaktionsarbeit zu machen aber dann konnten Leute elementare Sachen nicht machen (welche weiß ich auch nicht mehr) und dann hab ich die Rolle mit mehr Rechten etwas wahllos verteilt.
