### ISSUE TITLE
Shop Versandpreise

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#86]
Bei dem Vesuch neue Portogebühren einzutragen ist aufgefallen, dass die Preise für den Versand innerhalb Deutschlands unter "Europa" eingetragen sind aber man nicht zwischen Europa und Deutschland differenzieren kann. Ist anscheinend bisher niemandem inkl. mir aufgefallen... Kann man das ändern?

**Comment by divanke** [comment]
Hallo Isabelle,

im Backend von Prestashop lassen sich unter Lokalisierung -> Gebiete die
Regionen editieren, die (z.B.) für den Postversand verwendet werden. Ich
habe dort Deutschland hinzugefügt, jetzt ist des unter Versand auch
verfügbar, so dass du zwischen Deutschland, Europa und Europa(Nicht-EU)
die Versandkosten differenzieren kannst.

Liebe Grüße,

Anke


Am 01.06.21 um 16:25 schrieb ibartram:

**Comment by ibartram** [comment]
Danke!
