### ISSUE TITLE
Redaktionsrechte/rollen

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#87]
Es ist ein Problem aufgetaucht, hier die Beschreibung

gibt es eine maximale anzahl von änderungen, die vorgenommen werden kann? 
die fehlermeldung sagt folgendes: 
"   Either the path '/node/4039' is invalid or you do not have access to it.
    Der Inhalt wurde entweder von einem anderen Benutzer bearbeitet oder Sie haben schon Änderungen gespeichert. Deshalb können diese Änderungen nicht gespeichert werden. "

Woran liegt das? An der einschränkung der Rechte für Redakteur*innen? Wenn ja denn bitte ändern.

**Comment by divanke** [comment]
Hallo Isabelle, 
ich glaube nicht, dass es eine maximale Anzahl an Änderungen gibt. Die Fehlermeldung klingt ziemlich kryptisch (bzw. wie eine schlechte Übersetzung) ... Bei welcher Aktion trat der Fehler denn auf? Es gibt offenbar zwei Artikel mit dem Titel "Für reproduktive Gerechtigkeit", einen von Taleo Stüve, der veröffentlicht ist, und einen von dir, der noch nicht publiziert ist. Dein Artikel gehört zum /node/4039 (das ist sozusagen der interne Name/die Adresse), und ich vermute, dass es daran liegt, dass er von dir noch nicht veröffentlicht wurde und andere Benutzer damit keine Berechtigung haben, darauf zuzugreifen. Kann das sein?
Wenn ich genauer weiß, bei welcher Aktion die Fehlermeldung auftrat, kann ich evtl die Berechtigungen entsprechend anpassen. Eigentlich sehen die nämlich ganz okay aus...
Liebe Grüße, 
Anke

**Comment by ibartram** [comment]
Mir ist ein fehler im Post einer Kollegin aufgefallen (Autor*in fehlt), ich hab leider keine Rechte ihn zu ändern, wa sungünstig ist weil die Kollegin grade nur noch 1x die Woche arbeitet. Könnte ich Rechte bekommen? Danke!
https://www.gen-ethisches-netzwerk.de/petition-keine-patente-auf-saatgut-ministerinnenkonferenz-jetzt

**Comment by ibartram** [comment]
Achso, Judith hat mir grad erklärt warum ich das nicht ändern kann.
