### ISSUE TITLE
Shop Kund*innendaten exportieren

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#88]
Liebe Anke,
im Shop kann man unter Kunden eine Exceltabelle mit Kund*innendaten exportieren. Ist es möglich dort einzustellen, dass auch das Geburtsdatum der Kund*innen drin ist?
Danke & liebe Grüße

**Comment by divanke** [comment]
Hallo Isabelle, 
sorry, bin erst jetzt dazu gekommen. Im Backend vom Shop kannst du jetzt unter Erweiterte Einstellungen -> SQL-Abfragen eine Datenbankabfrage machen, in der das Geburtsdatum enthalten ist. Ist das so ausreichend? Liebe Grüße, 
Anke

**Comment by ibartram** [comment]
danke! könntest du da bitte noch die abfrage der adresse und die telefonnummer einfügen?

**Comment by divanke** [comment]
Hallo Isabelle, 
es ist mir nicht gelungen, in die existierende Abfrage Adresse & Telefonnummer einzufügen, da sie in einer anderen Tabelle gespeichert sind. Daher habe ich eine neue Abfrage erstellt, in der nun aber zwei andere Infos fehlen: 

Anrede (ist in der alten Abfrage bei allen Einträgen leer)
Umsätze

Gib mir doch bitte Bescheid, falls sie dir fehlen.

**Comment by ibartram** [comment]
super, danke!
