### ISSUE TITLE
Themensortierung

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#89]
Wie sind grade dabei zu überlegen die Themen zu überarbeiten, also wo wir die Artikel einsortieren. Falls wir ein bisschen umsortieren, also z.B. ein Unterthema von "Agrogentechnik" zu "Gene und Genome" umschieben, was wäre die Auswirkung? Grade ist es ja so, dass alle Artikel die Unterthemen in der URL automatisch haben, weil Oli mal meinet das sei wegen SEO besser? Aus jeden Fall wäre die Frage ob sich die Links der Artikel ändern würden, das wäre natürlich nicht so gut falls die schon irgendwo verlinkt werden. Auch falls wir ein Thema ganz löschen und die Artikel wo anders einsortieren, würden sich das dann die URLs der betroffenen Artikel noch mal ändern? Danke schon mal!

**Comment by divanke** [comment]
Hallo Isabelle, unter Konfiguration -> Suche & Metadaten -> URL redirects findest du eine Liste der redirects, die automatisch erstellt werden: immer, wenn z.B. der Titel eines Artikels verändert wird oder ein Stichwort hinzugefügt wird, ändert sich der Link/die Adresse des Artikels und hier wird dann eine permanente Weiterleitung vom alten zum neuen Link eingetragen. 
Wenn ihr, wie in deinem ersten Beispiel, ein Unterthema einem anderen Thema zuordnet, würde die Adresse/der Link gleich bleiben, weil dort ja nur der Name des Unterthemas bzw. der Unterthemen enthalten sind, nicht aber der Name des übergeordneten Themas. 
Wenn ihr ein Thema umbenennt (z.B. Versuchs-Freisetzungen in Versuchsfreisetzungen) bleibt der Link bei allen alten Artikeln erhalten (also mit Bindestrich), der Artikel wird trotzdem unter dem Thema Versuchsfreisetzungen (ohne Bindestrich) aufgelistet. Neue Artikel erhalten den neuen Namen des Themas in den Link, also Versuchsfreisetzungen. 
Wenn ihr ein Thema löscht, wird es in alten Artikeln nicht mehr im Themenkasten in der rechten Spalte angezeigt, taucht aber weiterhin als Begriff im Link zu dem Artikel auf. Das ändert sich erst, wenn ihr den Artikel editiert (egal an welcher Stelle, aber eben z.B. auch bei der Zuordnung eines neuen Themas). Diese Veränderungen im Link zum Artikel werden automatisch in die Liste der URL redirects aufgenommen und die Artikel bleiben so erreichbar. 


Weitere Versuche hab ich jetzt noch nicht gemacht - wenn du weitere Fragen hast, stell sie gern, dann probier ich das hier in der "Sandbox" aus, ohne dass ihr auf der Seite was "kaputt macht". 

Wie auch immer bringt eine größere Umgestaltung eventuell etwas Chaos in die Struktur. Aber es gibt Überarbeitungen, wie z.B. das von dir erstgenannte Beispiel, die keine sichtbaren Auswirkungen haben. 

Ich hoffe, das hilft weiter.
