### ISSUE TITLE
online-spenden

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#90]
Liebe Anke, könntest du auf der /spenden Seite das Twingle-Projekt "Gen-ethisches Netzwerk" und nicht "Artikelspenden" einbinden? Die "Artikelspenden" bitte nur auf den Popups bei Artikeln. Mir fehlt die Berechtigung das zu ändern. Danke!

**Comment by divanke** [comment]
Hallo Isabelle, ich habe das auf der Spendenseite verändert. Auf der Startseite wird auch das Twingle-Projekt "Gen-ethisches Netzwerk" angezeigt. Muss noch an anderer Stelle etwas verändert werden? Habe keine weiteren Stellen gefunden ...
