### ISSUE TITLE
Mahnungen verschicken im Shop

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#91]
Wir möchten gerne Mahnungen verschicken im Shopsystem. Ich hab dafür schon den Bestellstatus "Zahlung fehlt, Mahnung verschickt" angelegt. Aber ich hab keine Berechtigung eine neue E-mail-Vorlage dafür zu erstellen. Könntest du mir die Berechtigug geben?

**Comment by divanke** [comment]
Hallo Isabelle, im shop haben pia, du und ich die gleichen Berechtigungen. Das mit den Mail-Vorlagen scheint aber irgendwie komplizierter zu sein - es gibt eine Reihe von Vorlagen für die Mails, aber ich habe keine für eine Mahnung gefunden. Daher habe ich jetzt die Test-Mail, die du offenbar übergangsweise eingetragen hattest, per ftp kopiert und als "reminder" gespeichert. Jetzt kannst du diese "Vorlage" nach deinen Vorstellungen verändern. Dazu gehst du zu Lokalisierung -> Übersetzungen -> Übersetzungen ändern -> Programmteil: E-Mail-Vorlagen, Template: (je nach dem welches sonst verwendet wird - weiß ich nicht), Sprache: Deutsch. Sehr unintuitiv, gebe ich zu. (Habe ich hier gefunden: https://belvg.com/blog/how-to-edit-email-templates-in-prestashop-1-7.html ) Ich hoffe, das hilft weiter! Frag gern nach.

**Comment by divanke** [comment]
Nachtrag: offenbar müssen html-Mail und Text-Mail unabhängig voneinander angepasst werden ...

**Comment by ibartram** [comment]
Hmmh.. also ich hab den Text geändert und gespeichert und auch noch mal nachgeschaut, da war er so wie ihn wollte. Aber wenn ich bei Bestellungen > Status die Mailvorlage "reminder" ausgewählt hab und mir hab anzeigen lassen, dann war da wider der alte text. Und wenn ich zuück gegangen bin dort wo man den Text ändern kann war meine Veränderung weg?! Seltsam? 

Ich will diesen Text: 



Zahlungserinnerung Bestellung beim Gen-ethischen               Netzwerk e.V.
--
 
Sehr geehrte*r Kund*in,  

vielen Dank für Ihre Bestellung bei Gen-ethischen Netzwerk e.V.  Bisher konnten wir leider noch keinen Zahlungseingang für Ihre Bestellung zuordnen (Rechnung im Anhang). Bitte überweisen Sie den ausstehenden Betrag unter Angabe der Rechnungs-Nummer innerhalb der nächsten 14 Tage auf das angegebene Konto.  Mit einer fristgerechten Überweisung helfen Sie uns, Verwaltungs- und Mahnkosten möglichst gering zu halten.  

Sollte der Betrag von Ihnen in den letzten Tagen überwiesen worden sein, Sie dieses Schreiben bitte als gegenstandslos. Vielen 

Danke für Ihr Interesse und beste Grüßen von GeN und GiD    



Am besten wäre noch wenn man personalisierte Elemente nehmen könnte wie den Namen der Person und die Rechnungsnummer und den Rechnungsbetrag, aber das ist zweitranging.

**Comment by ibartram** [comment]
also Kunde/in mit Sternchen gegendert

**Comment by divanke** [comment]
Hey Isabelle, 
Das lag daran, dass die Version für das Template, dass ihr im Shop benutzt (classic-sub), nicht angepasst war. Ich habe es jetzt auch für das Template classic-sub eingetragen und jetzt wird es in der Vorschau angezeigt. Die Schnipsel für Name & Rechnungsnummer lassen sich bei anderen Übersetzungen abschreiben, z.B. payment. Das sind die Sachen in den geschweiften Klammern, z.B. {name} für Nachname und {order_name} für Rechnungsnummer.
