### ISSUE TITLE
kein Patente auf leben Petitionsblock

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#92]
Ich scheine leider keine Berechtigung zu haben den "Kein Patent auf Leben!"-Block auf der Startseite zu entfernen? Er soll auf jeden Fall weg, die Petition ist vorbei. Könnte ich die Berechtigung haben sowas zu machen falls es daran liegt? Danke!

**Comment by divanke** [comment]
Ja, dir fehlte die Berechtigung dazu, sorry. Ich habe alle Veränderungen an der Startseite jetzt für alle Redaktionsadmins freigegeben. Jetzt solltest du den Text aus dem Kasten entfernen können.
