### ISSUE TITLE
login c-panel

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#93]
Ich kann mich grad nicht einloggen obwohl ich das aktuelle passwort hab, und en richtigen username verwende. es sagt immer "protokoll ungültig", auch wenn ich einen anderen browser verwende. wie kann es sein? was mache ich falsch? bei meinen Kolleg*innen klappt es.

**Comment by divanke** [comment]
Hallo Isabelle,

ne richtig gute Idee hab ich nicht... Weil du Protokoll schreibst: hast du am Anfang der Adresse https statt http angegeben? Also
https://gen-eth....de:2083

Eigentlich sollte es eine automatische Weiterleitung nach https geben... 

Wenn das nicht hilft, melde dich gern nochmal!

Liebe Grüße von Pellworm,

Anke 

Am 9. August 2021 14:22:34 MESZ schrieb ibartram ***@***.***>:

**Comment by ibartram** [comment]
Nee er sagt immer noch Protokoll ungültig?! Ich geh über https

**Comment by ibartram** [comment]
Ich hab es versucht über 
https://cpanel.gen-ethisches-netzwerk.de/
https://gen-ethisches-netzwerk.de:2083/
https://saturn.planetary-networks.de:2083/
login gengid und das richtige passwort
bei kolleg*innen klappt es, bei mir weder in firefox noch in chrome.

**Comment by ibartram** [comment]
hab  dir einen screenshot geschickt

**Comment by divanke** [comment]
Danke. Ich habe den Verdacht, dass die Firewall des servers deine IP-Adresse blockiert. Ich habe deswegen mal an Dennis von Planetary Networks geschrieben, ich hoffe, er kann weiterhelfen. Evtl muss ich dich deshalb nochmal nach deiner IP-Adresse fragen ...

**Comment by divanke** [comment]
Dennis hat auch keine weiteren Ideen, braucht aber für den Check, ob meine Vermutung richtig ist, deine IP. Könntest du sie hier rausfinden und mir schicken? https://www.whatismyip.com/ 

Evtl könnte es auch helfen, wenn du deinen Router, über den du ins Netz gehst, neu zu starten - 10 sekunden Stromstecker ziehen und wieder einstöpseln sollte dafür reichen. Dann wird dir i.d.R. eine neue IP-Adresse zugewiesen.

**Comment by ibartram** [comment]
also das problem ist gelöst!!! ich hatte ein faslche spasswort bekommen von meiner kolegin, 2 falsche faslche passwörter... und dann ein richtiges aber dann vl an dem tag zu oft versucht? und später nur die 2 falschen ausprobiert??? sorry für die umstände, es war einfach nicht erklärbar für mich.

**Comment by divanke** [comment]
Ah, gut, dass das Rätsel geklärt ist - das ist ja die einfachste Lösung. :)
