### ISSUE TITLE
GID-Archiv

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#94]
Wir haben folgende Mail bekommen:

"Ich bin technisch nicht versiert, aber es könnte auch sein, dass eure Website eine Fehlfunktion provoziert, vielleicht auch nur bei bestimmten Browsern: Bei der Recherche über euer Menu (“Publikationen” > “Gen-ethischer Informationsdienst”) und die Suchfunktion ("Jahrgang XY anzeigen”) war und ist es mir nicht möglich, die einzelnen Artikel der archivierten GiD-Ausgaben aufzurufen. Mit Ausnahme der ersten Archiv-Seite werden nämlich unter den Titelbildern gar keine Artikel angezeigt (siehe Screenshot). Ich habe das jeweils mit dem Safari- und dem Firefox-Browser ausprobiert, das Problem besteht bei beiden. Vielleicht lässt sich das ja auf eurer Seite beheben, so dass die älteren Ausgaben voll recherchierter bleiben."

Woran könnte das liegen? bei mir (Firefox) besteht das Problem nicht.

**Comment by divanke** [comment]
Kannst du mir bitte auch dazu den Screenshot aus der Mail zuschicken? Danke!

**Comment by ibartram** [comment]
hat sich erledigt, war ein fehler von der person :)
