### ISSUE TITLE
E-mail Signatur

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#95]
siehe meine Mail vom 13.09. - Hife bei einheitlichen HTML-Signaturen für alle im GeN

**Comment by ibartram** [comment]
Folgende Änderungswünsche gab es zu deinem letzten html-Signaturentwurf

- doch keine Symbole/Bilder weil sie werden nicht angezeigt in einigen Mailprogrammen
- Schrift unter dem Strich (Vereinregister) kleiner - gleiche Schriftgröße wie Kontaktdaten, insgesamt nur 2 Schriftgrößen, Namen groß, Rest klein
- Aktueller GID sollte mit rein - unter Namen/ Kontaktdaten und über dem Strich, grade: "aktueller GID Nr. 259: Baumwolle – Die fragwürdige Erfolgsgeschichte der Gentechnik" - den Teil nach dem Doppelpunkt verlinkt auf https://www.gen-ethisches-netzwerk.de/publikationen/gid/259

Danke!

**Comment by divanke** [comment]
Hallo Isabelle,

wenn keine Symbole/Bilder im Footer vorkommen sollen, gilt das auch für
die kleinen Symbole vor Telefonnummer, Adresse etc? Dann würde ich den
Code dort noch vereinfachen, damit ihr darin einfacher selbst Änderungen
vornehmen könnt. Wenn das Twitter-Symbol wegfällt, soll trotzdem der
Twitter Link noch vorkommen?
Den aktuellen GiD kann ich einfügen.

Liebe Grüße, Anke


Am 30.11.21 um 13:35 schrieb ibartram:

**Comment by ibartram** [comment]
Danke, ja das gilt besonders für die kleinen Symbole, bei mir im thunderbird werden die standardmäßig als schwarze Blöcke angezeigt, bei anderen anscheidenend auch. Twitter als Link  und nicht als Bild ist gut. Ist schade mit den Symbolen, aber wenn es bei Hälfte der leute blöd aussieht dann bringt es nichts.

**Comment by divanke** [comment]
Hallo Isabelle,

gut, dann hier die Signatur ohne Bilder.  Falls noch Fragen oder Wünsche
auftauchen, sag gern Bescheid! Liebe Grüße,

Anke

Am 07.12.21 um 13:11 schrieb ibartram:
> Danke, ja das gilt besonders für die kleinen Symbole, bei mir im thunderbird werden die standardmäßig als schwarze Blöcke angezeigt, bei anderen anscheidenend auch. Twitter als Link  und nicht als Bild ist gut. Ist schade mit den Symbolen, aber wenn es bei Hälfte der leute blöd aussieht dann bringt es nichts.
>
