### ISSUE TITLE
Darstellung Autor*innennamen

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#98]
Bei mehreren Autor*innen fehlen die Kommas zwischen den Namen, z.B. hier
https://www.gen-ethisches-netzwerk.de/peter-wehling

Auf der Startseite sind bei GID-Artikeln, nicht bei Online-Artikeln die Autor*innennamen nicht mehr verlinkt, bitte wieder ändern. Danke!

**Comment by divanke** [comment]
Hallo Isabelle,

Danke für den Hinweis! Das Komma wurde vor der Aktualisierung durch ein
Plugin gesetzt, was nicht mehr mit der neuen Version funktioniert. Mir
war die Funktion des Pugins auf der Seite nicht klar, es war mir nicht
aufgefallen, dass die Kommata fehlten. Ich habe es jetzt über einen
anderen Weg gelöst, dass die Kommata angezeigt werden. Falls dir weitere
Details auffallen, gib mir gern Bescheid!

Danke,
Anke


Am 30.11.21 um 13:26 schrieb ibartram:

**Comment by divanke** [comment]
Und die Verlinkung ist jetzt auch wieder da.
