### ISSUE TITLE
Shop: maximale Bestellmenge

### ISSUE THREAD

**Issue by ibartram** [gengid/ticket#99]
Kann man irgendwie die Bestellmenge auf 3 begrenzen? Ich seh nur dass man einstellen kann, dass man _mindestens_ x bestellen muss. https://shop.gen-ethisches-netzwerk.de/broschuere/90-gentechnik-im-kleiderschrank.html

**Comment by divanke** [comment]
Hey Isabelle, sorry, habe diese Anfrage irgendwie übersehen ... 
Es gibt einige module, die das ermöglichen, die kosten aber >40€. Abgesehen davon habe ich eine Möglichkeit gesehen, die _für alle Produkte_ die Bestellmenge auf einen bestimmten Max-Wert beschränken kann, aber eben nicht für ein einzelnes Produkt. Was denkst du dazu?
